### ISSUE TITLE
workshop: team documentation processes

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1412]
### Goals
The goal is not to consolidate documentation into one tool; rather, it's to define a clear, viable process for the team to work in both Google Drive & Sharepoint.
### Tasks
- [x] Create a workflow diagram of the current state (Amy)
- [x] Reach out to the VRO, CC, and BDEx team to learn about their processes (Christine)

### Upcoming Tasks
- [x] Plan for workshop (Christine, Amy)
- [x] In workshop, brainstorm how we might close gaps that were identified in current processes **(Christine, Yang, Ilya, Amy)**

### Notes:
- slack thread: https://dsva.slack.com/archives/C01BVF2A3V0/p1680807181682079
- [summary of our challenges, constraints, and the start of a process proposal](https://docs.google.com/document/d/1a_qxm_codfGgjb5M2BhVwci0jAa_NbLLIQmWnXl87Bw/edit?usp=sharing)

**Comment by amylai-nava** [comment]
Moving from Sprint T --> Sprint U

**Comment by amylai-nava** [comment]
@ChristineRoseSteiffer I'm considering the workshop part of this work done! created a new task to track synthesis + next steps.
