### ISSUE TITLE
Write up research report - htn exploratory research

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1463]
We did research, we need to document and share what we learned. 

```[tasklist]
### Tasks
- [x] @carodew to write up outline
- [x] @ChristineRoseSteiffer to start filling in sections
- [ ] Review and align
```

**Comment by amylai-nava** [comment]
Marking this as done since [the research report has been shared.](https://dsva.slack.com/archives/C01AXBZA3QR/p1682723899000589)
