### ISSUE TITLE
data exploration: claims processing time for each phase in the claim life cycle

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1567]
We want to get a better understanding of claims processing time for each phase in the claim life cycle to 1) support background research for our next product bet, 2) get more familiar with claims data, and 3) build relationships with the PA&I team.

### Tasks
- [x] Meet with Phil H. to learn about transaction time data & past analyses
- [x] Review the 2015 "squeeze" analysis 
- [x] Review the FY23 cycle time by backlog status and deferrals data
- [x] Follow up with Phil on clarifying questions about the FY23 data^

### Clarifying questions on FY23 data
- Is there a way to look at the "development" phase more granularly?
- Could we look at additional attributes, such as
  - How many of the claims were new/original claims?
  - What were the contentions on the claim?
  - What record requests were made?
  - How many exams were ordered?
  - What were the reasons for deferral?
