### ISSUE TITLE
Support solution decision for subscribing to contention events (BIP or EventBus, or both?)

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1576]
### User Story

As a VRO Product Owner, I want to determine the best service to use to get access to event streams of claim-relevant data (starting with contention events), so that my team can integrate with that service accordingly.

### Acceptance Criteria

1. Premal has been provided a recommendation with supporting rationale for how to proceed with subscribing to one or both eventing services.

**Not included in this work**

Implementing an event stream subscription.

**Notes about work**
- Initial work to connect to the BIP event streams in the DEV environment was completed in #1159 
- We have a meeting with the [Event Bus](https://github.com/department-of-veterans-affairs/VES/blob/master/research/Event%20Bus/README.md) team on 5/26 to learn more about each other's work and determine if it would be a good partnership for both sides
- The most immediate use case for subscribing to contention events is to support the CC team's post-launch success measurement. More broadly, we have a hypothesis that if we can get visibility into real-time contention events it will make future product direction and scoping decisions easier for partner product teams.

```[tasklist]
### Tasks for technical input:
- [ ] Review [BIE kafka documentation](https://community.max.gov/pages/viewpage.action?spaceKey=VAExternal&title=Benefits+Integration+Events) and related tickets (#1159 and #646), as well as [Event Bus documentation](https://github.com/department-of-veterans-affairs/VES/blob/master/research/Event%20Bus/README.md) before Friday 5/26
- [x] Attend call with Event Bus team on Friday 5/26 (8am PT)
- [ ] Review #1642 and help break down an initial set of child tickets
```

**Comment by pshahVA** [comment]
Some things I would like to understand better:
 What value does this VES solution add, compared to connecting directly to the BIA stream?
 What value can VRO add to this integration? Would we add more technical infrastructure? Just document that it exists?

**Comment by dianagriffin** [comment]
Immediate solution decision to support CC team's success measurement use case in the near-term (2023) = we will pursue integration with the BIE kafka service while continuing discussions about partnering with EventBus in parallel as potentially our preferred long-term solution for event subscription.

Next steps are covered by #1642 ; closing this ticket as complete.
