### ISSUE TITLE
Prepare for Veteran research

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1712]
We want to conduct research with Veterans to:
- learn what language Veterans use when referring to their ratings and submitting claims for increase (CFI)
- understand why they might submit a CFI when they are already at the max rating
- do concept testing around what copy changes might change their behavior

## Tasks

- [x] Review past research down by VFS teams on [va.gov github repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023_feb)
**Note:** according to [CC team notes](https://docs.google.com/document/d/1vtSqrV486HKXYynhjKm2qG20CgpTxog0QA8BHKNoUAg/edit#heading=h.3cqtvbuaxqdo), February 2019 and July 2019 reports specifically have to do with contentions
- [x] Review Veteran discussion boards (e.g., Reddit)
- [x] Coordinate with the Contention Classification team since they are also planning to do Veteran research
- [x] Using input from above, put together a research plan and get feedback from the team
- [x] Submit research plan to Peregian

## Open questions 
- How many users fill out this form on a desktop screen versus a mobile or tablet screen? 

## Related issues
#1733

**Comment by carodew** [comment]
One plan @KimLadin and I are discussing is doing a very quick, minimal round of research just testing for our main deal breaker (we have no impact on veteran behavior) while also planning a follow up study to go more in depth on preference testing, mobile users, and users of assistive technology.

**Comment by amylai-nava** [comment]
@ChristineRoseSteiffer added you as an assignee since you're also working on this!

**Comment by amylai-nava** [comment]
note to self for status report: began in sprint X, continuing in sprint Y
