### ISSUE TITLE
Concept sketching for veteran research

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#1733]
## Background

We need some concept sketches to show to Veterans for research done in #1712. We need to test against the dealbreaker that our intervention would have no impact on Veteran behavior in terms of submitting CFIs when they are already at the schedular maximum. We want to do this sketching for mobile first to force us to simplify.

At the same time, we don't want to prevent or discourage valid claims (e.g. for IE or extra-schedular ratings). 

Secondary goal: preference testing on different concepts? 

```[tasklist]
### Tasks
- [x] Identify places in the application process where we could intervene
- [x] Find out if there are limitations on where we can intervene (technical or policy limitations?)
- [x] Figure out what kind of collaboration we want to do with the claimant experience team (check in with Sudeepti, Eva, Lydia)
- [x] Develop some rapid concept sketches and articulate hypotheses for how it will impact veteran behavior
- [x] Find examples within the VA of this kind of messaging (instructional form text, "You might want to think about this in your file"
- [x] Review sketches with the design team
- [x] Incorporate feedback
- [x] Prep for testing
```

### Open questions
**Test with mobile phones / AT users?** 
  - On the one hand, this doesn't help us understand if we've passed our deal breaker in the most lean way possible. However, excluding mobile users would mean we would not get important information on how we can refine our designs before production. Screen readers -- we would likely need to test this in HTML, so may need to come later. (Note, va.gov recommends a mobile-first approach) 

- **What's the relationship between tinnitus and hearing loss? VSRs are also looking for signs of hearing loss in the evidence when they get a tinnitus claim ... is it fair that this mostly impacts initial claims, and not CFIs?**  
- **What's the impact of IU and other extra-schedular ratings?** 

### Timeline

- Set up collaboration check ins? 
  - collaboration cycle? 
  - CE team?   
- Get access to design files
- Create initial sketches
- Get feedback from EE design team, CE design team, etc? 
- Refine sketches for use in research

### Related issues
#1712 (interviews to begin July 12)

### Resources

- [va.gov 526EZ application flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?invited=true&sender=carolyn1198)
- [m-21 section on tinnitus](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000014464/M21-1-Part-V-Subpart-iii-Chapter-2-Section-B-Conditions-of-the-Auditory-System?query=tinnitus#3)
- [rating schedule for ear conditions](https://www.ecfr.gov/current/title-38/chapter-I/part-4/subpart-B/subject-group-ECFR378242b2776122d/section-4.87)
- [Product brief](https://docs.google.com/document/d/11-L6dbZ7Hah-e2PL3-nfcN5c5T8uAbn3EumLikrEhV4/edit#heading=h.v3g0dltmvazl)

**Comment by carodew** [comment]
Language from decision letter: 

> We have assigned a 10 percent evaluation for your tinnitus based on:
> • Recurrent
> A single evaluation for recurrent tinnitus is assigned whether the sound is perceived in one ear, both ears, or in the head.
> This is the highest schedular evaluation allowed under the law for tinnitus. (38 CFR 4.87)

**Comment by amylai-nava** [comment]
note to self for status report: began in sprint X, continuing in sprint Y

**Comment by amylai-nava** [comment]
@carodew considering this done!
