### ISSUE TITLE
Determine approach for metrics tracking

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1822]
```[tasklist]
### Tasks
- [x] Turn on the ads console to see what events are currently being tracked (see [slack thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1689887618215649))
- [x] Submit a github request for any custom events we need ([request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62370) submitted on 7/20)
- [x] Investigate how we might track the data we need for our metrics in vets-api
```

### Data we're interested in:
- Number of people who see our education vs. don't
  - Of those who see our education, the number of people who file a claim while already at the max dating
  - Of those who don't see our education, the number of people who file a claim while already at the max rating
- The usual claim-level data for those claims: claim ID, submission date, submission time, etc.
- `Nice-to-have:` Number of va.gov tinnitus CFI submitted while at a 0% rating

### Resources
* [related slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1689717944449859?thread_ts=1689612337.394009&cid=C1Q4294JJ)
* instructions on how to use the [ads console](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/frequently-asked-questions)
* template for the [github request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BProduct%5D)

**Comment by amylai-nava** [comment]
Request submitted on 7/20: https://github.com/department-of-veterans-affairs/va.gov-team/issues/62370

Given that they're a little backed up, I think it would be worth looking into how we can track our metrics on the back end. @nanotone, can I assign this to you to investigate?

**Comment by amylai-nava** [comment]
✅ approach determined
➡️ @nanotone to create a ticket for the implementation
