### ISSUE TITLE
Research plan + conversation guide for usability testing

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2156]
This ticket covers starting the documentation for our next round of research to refine the final max CFI design we'd like to implement in production.

- [x] Start draft of research plan
- [x] Start draft of conversation guide
- [x] Start determining recruiting criteria

```[tasklist]
### Tasks
```

**Comment by meganhicks** [comment]
The team suggested that we are not close to being able to do this yet.  They said useability testing was set up for early December and they suspect this will not happen due to waiting for the CAIA meeting. This will push the ticket back to early January. I am moving the ticket to the backlog.

**Comment by ChristineRoseSteiffer** [comment]
[Research Plan Draft](https://docs.google.com/document/d/11xU9ypB5Rh25f26kr37E3xS5akWjDxPwA3ak36mPk4Y/edit)
[Convo Guide Draft](https://docs.google.com/document/d/17QusaRi1LLeGvhUaK6gnbarjW5cb1PpthHNg_-ChyJw/edit)
