### ISSUE TITLE
Set up skeleton prototype in Codepen

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2157]
dependent on https://github.com/department-of-veterans-affairs/abd-vro/issues/2155

We want a codepen prototype of the current intervention. We want this because the research indicates that is where we should focus. 

Designers note: in most cases, if the default VA design system components differ slightly from the Figma file, go with the design system component. The main differences will be the progress bar and the checkbox tiles. 

```[tasklist]
### Tasks
- [x] Build skeleton of Scenario 1: multiple accordions
- [x] Build skeleton of Scenario 2: link to external page (forthcoming)
- [x] Build skeleton of Prototype main menu (forthcoming)
```

## Design files
- [Mock up of Scenario 1: multiple accordions](https://www.figma.com/file/ZGsQLRV5tUTh1QJPCqefap/Max-CFI-design-refinements?type=design&node-id=0-251&mode=design
)

- [Mock up of Scenario 2: link to external page](https://www.figma.com/file/ZGsQLRV5tUTh1QJPCqefap/Max-CFI-design-refinements?type=design&node-id=0-2159&mode=design) (Note: I need to check on whether we want to have some type of breadcrumb or other navigation elements at the top of the external page, will update when I've figured that out). 

- [Start page and end of prototype page](https://www.figma.com/file/ZGsQLRV5tUTh1QJPCqefap/Max-CFI-design-refinements?type=design&node-id=0-3&mode=design)
