### ISSUE TITLE
Ratings Process Research to inform LOE on Max ratings API

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2205]
_Note: this ticket may need to be split into smaller tickets_

## Goal
Estimate the rating level of effort for displaying the maximum rating for all conditions on the Rated Disabilities screen within the 526EZ form.

## Open questions

```[tasklist]
### Tasks
- [x] How is the max rating determined for hyphenated and analogous conditions?
- [x] How do we handle scenarios where there's a major and a minor rating?
- [x] How many diagnostic codes are there? How often does the max rating change?
- [x] How often to schedules change? AND How much notice do we receive?
```

AC:  The questions have been answered and there is a plan to present the information to the team and relevant stakeholders. 

## Future Ideas
- Display the max rating for all conditions, regardless if the Veteran is already at the max rating. Don't display the max rating for hyphenated conditions.
- Display the max rating educational text only if the Veteran is already at the max
- _others?_

## Notes
- from [11/9 stakeholder sync discussion ](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Employee%20Experience/Shared%20Meeting%20Notes/New%20-%20VBA%20Stakeholder%20Sync%20Notes.docx?d=w96109afbf1ff4f28826a54fe2e5a8ece&csf=1&web=1&e=MiVAjg) (in sharepoint)

**Comment by amylai-nava** [comment]
@KimLadin considering this done based on your update yesterday!
