### ISSUE TITLE
Refine max CFI designs based on feedback from Platform team (Collab cycle design intent)

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#2261]
We received feedback from the Platform team from the Design intent. We need to refine our max CFI designs to respond to that feedback and prepare for usability testing. This is that ticket. 

```[tasklist]
### Feedback from Design intent
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70061
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69941
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69924
```

```[tasklist]
### Tasks
- [x] Compile feedback from Platform team and decide on how to address each one
- [x] Explore a few different options based on that feedback
- [x] Get feedback from DBEE and 526 team
- [x] Decide on what versions we want to go into usability testing with
```

### Does not include: 
* Responding from feedback from / collaborating with CAIA team. We'll capture that in a separate ticket. 

### We know we're done when
We've decided what to go into usability testing with.

**Comment by carodew** [comment]
This is effectively complete, however I have one question for the Platform team on https://github.com/department-of-veterans-affairs/va.gov-team/issues/69924, so I haven't closed that ticket. However I'm moving this to done (rounding up from 99.99 percent complete).
