### ISSUE TITLE
Setup VRO DB entities for partner team use of alembic for DB migrations

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#2329]
As a VRO platform developer, my goal is to empower partner teams in handling their data migrations independently. This ensures they have the freedom to select the most convenient method tailored to their application's language, offering them flexibility and adaptability. By utilizing the Alembic tool, the CC team can efficiently manage their databases and maintain data organization with ease.

Acceptance Criteria
1. The following criteria should hold for both local and LHDI environments:
2. A new Postgres schema is created for use by the CC team
3. A new DB user with superuser privileges only for the schema from 1 is created with credentials propagated stored in HashiCorp vault and propagated to the K8s cluster.
4. References for these credentials are communicated to the CC team, including context on the expectation that CC owns it from here. The CC Team has asked for a pairing session for this.
5. Documentation is created for this offering from a VRO perspective under partner team documentation in the wiki - https://github.com/department-of-veterans-affairs/abd-vro/wiki

Notes about work
To complete this work, an engineer will need to log into the RDS postgres instance in each of our LHDI environments and use psql to manipulate the instances to satisfy the AC. This can be done by creating a shell into one of the running pods in the cluster namespace, installing psql as a CLI tool if necessary, and issuing the proper psql commands.

**Task list- please check off as you complete them**

- [x] 1. Use dev-tools pod to login with psql and create a new DB user and postgres schema for CC team
- [ ] 
- [x] 2. add secrets for the above user to Vault and k8s cluster
- [ ] 
- [x] 3. Give secret refs to CC team 
- [ ] 
- [x] 4. repeat for all envs
- [ ] 
- [ ] 5. Finish documentation
- 1 hour

**Comment by paulsackley-nava** [comment]
@Ponnia-M would like to pair on this

**Comment by agile-josiah** [comment]
So far steps 1 and 2 have been completed in dev will reach out to the CC team for a sync next week.

Vault/Lens Refs
Name: domain-cc-db
${DOMAIN_CC_PW}
${DOMAIN_CC_USER}

**Comment by agile-josiah** [comment]
https://github.com/department-of-veterans-affairs/abd-vro/pull/2808

**Comment by agile-josiah** [comment]
All lower environments completed. Will proceed with Prod once they are ready for it.

**Comment by meganhicks** [comment]
@agile-josiah I don't see that all the AC have been met. Can you please comment where you are at in terms of the AC 1-5 so we know in advance to planning what's left?

**Comment by agile-josiah** [comment]
Finishing production, creating documentation, and testing a successful connection in said environments.

**Comment by Dottifacilities** [comment]
Currently blocked by CC team deployment

**Comment by meganhicks** [comment]
We broke this out into 2 tickets. We now have one for E2E and deploy to prod. This ticket is waiting on documentation.

**Comment by agile-josiah** [comment]
https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Database#partner-team-database-migrations

**Comment by tejans24** [comment]
Adding a new link to reduce confusion: https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Partner-Team-Database-Migrations
