### ISSUE TITLE
Collab Cycle Mural updates and sharing

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2517]
This ticket is to cover:

```[tasklist]
### Tasks
- [x] Updates to the Mural based on our process
- [x] Ensuring Accessibility issues are covered
- [x] Set up time to share it out for feedback
```
