### ISSUE TITLE
Plan R/VSR interviews re: Max ratings, alternate pathways

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#2611]
Plan interviews with 3 claims processors in the field.

**Interview topics**
- How they handle CFIs that are already at the maximum rating
- What are the main ways Vets can get more compensation when they're at the maximum for a condition?
- How they decide on IU or ancillary services
- How Veterans request IU or ancillary services
- What they do when a Veteran requests IU or ancillary services in their 526EZ
- (if there's time) When and how they use hyphenated diagnostic codes

**Recruiting**
Speak to 1 VSR, 1 RVSR, and 1 Coach.
Offices to start with: Boise (RVSR), Montgomery (Coach Patty), and one other that we have contacts for

**Timeframe** 
Week of Feb. 19

**Format** 
1-hour interviews over Teams (must be on VPN in case they share PII/PHI)

**Tasks**
- [ ] Contact 3 offices for recruiting
- [ ] Schedule sessions
- [x] Write research plan / conversation guide

**Comment by KimLadin** [comment]
Interview 3 claims processors in the field to learn about:

- How they handle CFIs that are already at the maximum rating
- What are the main ways Vets can get more compensation when they're at the maximum for a condition?
- How they decide on IU or ancillary services
- How Veterans request IU or ancillary services
- What they do when a Veteran requests IU or ancillary services in their 526EZ
- (if there's time) When and how they use hyphenated diagnostic codes

Recruiting:
Speak to 1 VSR, 1 RVSR, and 1 Coach.
Offices to start with: Boise (RVSR), Montgomery (Coach Patty), and one other that we have contacts for

Timeframe: Feb 15-23

Format: 1-hour interviews over Teams (must be on VPN in case they share PII/PHI)

Tasks:

- [ ] Contact 3 offices for recruiting
- [ ] Schedule sessions
- [ ] Write research plan / conversation guide
