### ISSUE TITLE
Write up report for Max CFI Refinements Study

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2614]
```[tasklist]
### Tasks
- [ ] Draft insights into report
- [ ] Finalize report
- [ ] Share report
- [ ] Upload report to sharepoint & github
- [ ] Cleanup sharepoint files
```
