### ISSUE TITLE
Template - Epic 5. Research Review

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2663]
## Description
This ticket tracks what we need to do for the [research review](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#2-Research-review) process.

The Research Lead:
- [ ] submits a [research review ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=&labels=&template=new-research-intake.md&title=YYYY-MM+Title+of+Study) at least 10 business days before desired research kickoff
- [ ] submits a [recruiting ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=sstrassberg&labels=recruitment-criteria&projects=&template=recruitment+criteria.yaml&title=%5BRecruitment+Request%5D%3A+YYYY-MM+name+of+your+study) at least 10 business days before desired research kickoff. 
- [ ] Tags Shane/Kevin in the #research-ops Slack channel announcing the research effort and providing a link to the GitHub ticket.
- [ ] If Shane/Kevin request a meeting, set that up and invite designers, product managers, enablement team if needed

Research Ticket #
Recruiting Ticket # 

**Research Artifacts Needed**
- [ ] GitHub Folder created that includes:
- [ ] Research plan 
- [ ] Conversation guide 
- [ ] Mostly-done designs

```[tasklist]
### Tasks

```

```[tasklist]
### Dependencies

```

**After the meeting**
- [ ] Shane/Kevin will review the ticket and provide feedback, then kickoff the recruiting process
- [ ] Work with Perigean throughout recruiting
- [ ] Set up participant spreadsheet to track study progress
