### ISSUE TITLE
Template - Epic 7. Analytics Review

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2665]
## Description
This ticket tracks what we need to do for the [Analytics review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/analytics-request) process.

The Admin Support requests this touchpoint by submitting a ticket.
[Instructions](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/analytics-request)
[Ticket Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)

**Artifacts Needed**
- [ ] Product Outline
- [ ] North Star & Defined KPIs
- [ ] User interactions we want to track
- [ ] Authenticated test-user logins, when applicable (see note on platform page about how to provide these securely)
- [ ] Product URLs, including any unauthenticated landing pages that precede your tool.

Meeting required only if requested by the Analytics team in the ticket.

If requested, Admin support invites:
- Product Managers
- Enablement team
- FE Engineering point of contact
- Platform participants (Google tag manager specialists)
- Designers (optional)

```[tasklist]
### Tasks

```

```[tasklist]
### Dependencies

```

**After the meeting**
- [ ] Analytics team will help configure Google Analytics tracking for reporting and will support analyzing data
