### ISSUE TITLE
FY24 Q2 Partner Team Survey: Create and Launch 

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#2679]
**Description**
--
As a VRO Team and Platform performing other services for partner teams it is essential we conduct quarterly partner team surveys to capture their feedback in a formal way and cadence. 

**Why**
--
To compare our performance with the baseline we developed with the FY24 Q1 survey and ensure customer satisfaction and continuous improvement.

**AC**
--
1. Review the previous survey and make new survey form that can include minor changes or additional questions if needed, but ensure the survey stays consistent since it will be conducted quarterly
2. Develop comms and schedule reminders
3. Launch the survey via the #benefits-support-channel, tagging the CC and EE Team

**Notes**
--
- We only need to survey the EE and CC team developers and Product Managers

**Resources**
--
[Survey link](https://docs.google.com/forms/d/1fssxDT7BotV6fVCRdYW097ZC4bRwXLgedHorMgGn9O4/edit)

**Tasks**

- [x] Duplicate survey form
- [x] Review Q1 survey structure and (if needed) develop any new questions for Q2
- [x] Run new questions by Megan
- [x] Add new questions to survey
- [x] Develop comms for survey description and launch announcement
- [x] Develop schedule for launch and close date
- [x] Send survey to partner teams
- [x] Monitor data collection
- [x] Set up reminders for survey completion
- [ ] Close survey on due date

**Comment by meganhicks** [comment]
I would also argue we could close this.
