### ISSUE TITLE
Reach out to CC team regarding Collab Cycle epic tickets

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2681]
- [x] Reach out to CC team for their thoughts on converting our epic template tickets for the collab cycle to templates in GitHub
- [x] set up meeting with Bianca to discuss VRO impacts
- [x] Complete conversion of current tickets
