### ISSUE TITLE
Conduct secondary research on improving evidence submissions

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#2740]
```[tasklist]
### Tasks
- [x] Create Mural that references and synthesizes all previous research 
- [x] Create list of problems based on synthesis of research
- [x] Analyze problems on a scale of how many cases they affect and how much time the impact has
- [x] Determine next steps
- [x] Create draft research plan and convo guide for research with RVSRs and VSRs to answer more questions we have around evidence
```
