### ISSUE TITLE
Sprint Rocky Mountain

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2779]
<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW41QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dfa41766e11a8b9bc201e120f1c1bc5a5a87fe5/image.png" alt="image.png" />

Rocky Mountain National Park

Fun facts from Erik: 
- 40 min from his house 
- The park's elevation ranges from about 7,500 feet to over 14,000 feet.
- The highest point in the park is Longs Peak, which stands at 14,259 feet.
- Trail Ridge Road: This road is the highest continuous paved road in the United States, reaching an elevation of 12,183 feet.
- Erik has climbed Longs Peak 3x!

**Capacity:** 
Ponnia- out the 1st week of the sprint (3.25-3.29)
Cheng- out 3.26-3.28 
Erik- out the 1st week of the sprint (3.25-3.29)
Mason
Josiah 
Bianca
Megan
Bernie

**Sprint Metrics:** 

Sprint Goal: 
This sprint will focus on refining deployment processes and Secrel, conducting a comprehensive partner team survey, enhancing the BIE Kafka service for increased CC team utilization, and empowering the CC team with additional functionality by assisting them in independent database migrations through Alembic integration. By prioritizing these areas, we aim to fortify our platform's foundation and streamline collaboration across teams

First Priority: 
Pair on finishing any thing that rolled over. 

New Tickets in priority order:

- [ ] 1. Add ActorUserId field to RDS database #2724
- [ ] 2. Setup VRO DB entities for partner team use of alembic for DB migrations
- [x] 3. FY24 Q2 Partner Team Survey #2679
- [x] 4. Update svc-bie-kafka service wiki user guide#2791
- [ ] 5. ArgoCD Prototype Demonstrating Single Microservice Deployment #2781
- [ ] 6. Do not allow deployment to prod from workflows off the develop or main branch #2464
- [x] 7. Bug: Deployment to dev environment does not use the dev_ image #2470
- [x] 8. Move domain-rrd code into separate repo #2184
- [ ] 9. Documentation on debugging failed deployments #2343
- [x] 10. Eliminate the distinction between dev_* and other images #2759
- [ ] 11. Tech Spec w/ prototype: Re-configure Secrel workflow to allow signing of individual images-Pair to complete in 1 sprint #2472
- [ ] 12. Discovery to determine if we can remove some current deployments - first ticket #2580

**Demo:** 

Total Tickets: 12
