### ISSUE TITLE
Epic: Handling hyphenated conditions

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2784]
## Summary 

- When we check whether a Veteran's disability rating is at the maximum, we want to know whether the disability's diagnostic code is hyphenated, because that could impact whether we display the max rating notice --> handled by this ticket: https://github.com/department-of-veterans-affairs/abd-vro/issues/2768
- Update the max rating % according to the AC's below.
- This should all be behind a feature flag.
- Note: we won't have any changes on the VRO side of things, this is just within vets-api.

## Acceptance Criteria
- Maximum rating percentage is populated as follows: 
  - If the primary diagnostic code belongs to one of the following body systems, use the right hand code to determine the max rating:
    - Musculoskeletal (DCs 5000-5399)
    - Eye (DCs 6000-6099)
    - Auditory (DCs 6200-6299)
    - Respiratory (DCs 6500-6899)
    - Cardiovascular (DCs 7000-7199)
    - Genitourinary System (DCs 7500-7599)
    - Gynecological (DCs 7600-7699)
    - Hematologic/Lymphatic (DCs 7700-7799)
    - Skin (DCs 7800-7899)
    - Endocrine (DCs 7900-7999)
    - Neurological (DCs 8000-8999)
    - Mental (DCs 9200-9599)
    - Dental (DCs 9900-9999)
  - If the primary diagnostic code belongs to one of the following body systems, do not display a max rating:
    - Digestive (DCs 7200-7399)
    - Infectious Disease (DCs 6300-6399)
  - If the right code ends in *99, use left code to determine the max rating

## Notes about this work
- For details about each body system see this [summary document](https://docs.google.com/document/d/1rNgLPs1GoCaYgrpi4tIB6Ahe3dpukRCKKslSvojeEgg/edit?usp=sharing).
- The `primary diagnostic code` is the 4-digit code that is **to the right** of the hyphen 
- The `hyphenated diagnostic code` is the 4-digit code that is **to the left** of the hyphen

## Tasks
```[tasklist]
### Linked Issues
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2456
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2500
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2686
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2768
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2864
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2865
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2866
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/2809
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3066
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3230
```

**Comment by amylai-va** [comment]
@KimLadin @dfitchett @nanotone fyi, I've updated the AC with what we've discussed so far. It will need to be refined further once Kim has completed analysis of the other body systems.

**Comment by BerniXiongA6** [comment]
Hi @KimLadin -- could you provide @dfitchett and @nanotone with some more clarity about the AC bullets written above, particularly around the categories and sub-categories? That can help us get this ticket refined. Thanks!
