### ISSUE TITLE
Sprint S 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2834]
Sprint Sequoia National Park 

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEE5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6104e00cdb4ac4eed1731e98552fc64e51e09ae/image.png" alt="image.png" />

Facts: 
Located in California 
established on September 25, 1890
established to protect giant sequoia trees, the largest living trees by volume on Earth.
Megan's baby brother is there right now 

Previous Sprint Observations: 

- We attempted to plan our Sprint but half the team was out and we did not finish this exercise 
- When the other teammates arrived after being out, work was pulled in that did not align with the Sprint Goals and lots of work was completed out of priority order. 
Example: 
- Sprint R Tickets in priority order:
-Finished the Sprint R with 11 tickets completed, 8 in progress  

- [ ] 1. Add ActorUserId field to RDS database #2724
- [ ]  2. Setup VRO DB entities for partner team use of alembic for DB migrations
- [x]  3. FY24 Q2 Partner Team Survey #2679
- [x]  4. Update svc-bie-kafka service wiki user guide#2791
- [ ]  5. ArgoCD Prototype Demonstrating Single Microservice Deployment #2781
- [ ]  6. Do not allow deployment to prod from workflows off the develop or main branch #2464
- [x]  7. Bug: Deployment to dev environment does not use the dev_ image #2470
- [x]  8. Move domain-rrd code into separate repo #2184
- [ ]  9. Documentation on debugging failed deployments #2343
- [x]  10. Eliminate the distinction between dev_* and other images #2759
- [ ]  11. Tech Spec w/ prototype: Re-configure Secrel workflow to allow signing of individual images-Pair to complete in 1 sprint #2472
- [ ]  12. Discovery to determine if we can remove some current deployments - first ticket #2580
- In addition we added these to the Sprint and worked on them #2721, #2745, #2824 

**Capacity:**  April 9th- April 22

PTO:
- Teja 4/11, 4/12, 4/18
- Ponnia
- Cheng 4/18
- Erik
- Mason
- Josiah 
- Bianca
- Megan- I might take a have day sometime in next 2 weeks. 

Capacity Planning Calculator:
- All Engineering: reduced capacity of 46.9% in Sprint S (due to planned/known time off)
- All UX: reduced capacity of 71.4% in Sprint S (due to planned/known time off)
- All VRO Team: reduced capacity of 50% in Sprint S (due to planned/known time off)

**Sprint Goal:** 
Primary: Finish last sprint and wrap up the small deployment improvement epic we have

Who is on call: Secrel & dependabot and incident response 
On call Primary and Secondary #2835

**First Priority:** 

Pair on finishing work rolled over. 
Implement RBAC for `svc-bie-kafka` in our `dev`, `qa`, and `sandbox` environments#2530
Add ActorUserId field to RDS database#2724
Setup VRO DB entities for partner team use of alembic for DB migrations#2329
Discovery for flickering integration tests #2824
Remove camel code in xample-workflow app#2745
Setup Datadog User for RDS Monitoring#2504
Track Github action and its warnings#2721

New Tickets in priority order:

- [ ] 1. Implement RBAC for `svc-bie-kafka` in our prod environment#2560
- [ ] 2. Discovery on DORA metrics #2825
- [ ] 3. Discovery on creating a data storage retention policy for the VRO platform #2823
- [ ] 4. Tech Spec w/ prototype: Re-configure Secrel workflow to allow signing of individual images-Pair to complete in 1 sprint #2472
- [ ] 5. Discovery: Ensure graceful transition when k8s pods are evictted #2816
- [ ] 6. Do not allow deployment to prod from workflows off the develop or main branch #2464
- [ ] 7. Documentation on debugging failed deployments #2343
- [ ] 8. Discovery to determine if we can remove some current deployments - first ticket #2580
- [ ] 9. Top Use Cases: Deployment Requests & New Feature Requests - Research#2672
- [ ] 10. Top Use Cases: PRs and General Questions - Prototype Ideas#2730
