### ISSUE TITLE
Conduct reserach with claims adjudicators on evidence improvement

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2839]
```[tasklist]
### Tasks
- [ ] Finalize research plan and convo guide
- [ ] Schedule participants 
- [ ] Conduct interviews with 2 RVRs, 2 VRSs and 2 VROs
- [ ] Make a plan to develop a more regular partnership with the Montgomery office for future studies around evidence
- [ ] Synthesize what we learned
- [ ] Revisit the idea ranking mural to prioritize our options
- [ ] Determine our Next Big Idea in mural session with stakeholders
```
