### ISSUE TITLE
Prepare for and deliver presentation for Max CFI project on the weekly Design sync meeting

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2840]
```[tasklist]
### Tasks
- [ ] Review deck with Enablement team for feedback
- [ ] Update/finalize deck as needed
- [ ] Meet amongst ourselves to determine how we will present together
- [ ] Deliver presentation on Mon, Apr 22 at 1pm EST
- [ ] Upload to sharepoint & slack
```
