### ISSUE TITLE
Sprint T

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2884]
# Tonto National Forest, Arizona 
<img width="471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f0084418d81a09d781988edf8dbbeb3db4a57a5/image.png" alt="image.png" />
<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09ad4cb1bd1183c6ef43a0abfc8e191b22b7384d/image.png" alt="image.png" />

#### Facts: 
- 600,000 Acres 
- Home to 4 peaks which is on the back of all Arizona license plates 
- Home to Fossil Creek, known for its beautiful clear waters; magnificent fossil-like travertine rock formations; and diverse native fish, plants, and animals. The nearly 17-mile-long river is located in central Arizona on the Coconino and Tonto National Forests, approximately 100 miles from Phoenix.

## Capacity: 
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. _**Note: includes time off, non-sprint commitments, and new team member ramp-up.**_
- All Eng capacity reduced to 79%
- All UX capacity reduced to 85.7%
- All VRO Team capacity reduced to 80%

## Sprint Goal: 
Primary Goal: Finish RBAC for BIE all the way to production. This is crucial because we promised the CC Team we could wrap up their other open requests next Sprint. 

##Who is On Call? 
Cheng and Lisa 

## Sprint Tickets in Priority Order for Devs:

- [x] Implement RBAC for `svc-bie-kafka` in our in QA environment abd-vro #2847
- [x] Implement RBAC for `svc-bie-kafka` in our in sandbox environment abd-vro #2846
- [ ] Implement RBAC for `svc-bie-kafka` in our prod environment abd-vro #2560
- [x] Investigate why CC Application Went Down abd-vro #2883
- [x] Complete Alembic Setup for CC Team Use#2886
- [x] Partner with CC Team on Query abd-vro #2875
- [x] Setup Datadog User for RDS Monitoring abd-vro #2504
- [x] Update and clean up the VRO Diagram abd-vro #2770
- [ ] Tech spec: Develop an incident response plan abd-vro #2570
- [x] Fix Flickering **xample-domain / integration-test abd-vro #2345
- [x] Fix flickering *ee-ep-merge-end-to-end / integration-test abd-vro #2869
- [x] Remove unused code - svc-lighthouse-api abd-vro #2818
- [x] Discovery to determine if we can remove some current deployments - first ticket abd-vro #2580 and #2697

Removed:
Fix flickering svc-bie-kafka-end-to-end / integration-test abd-vro #2868

Added 
ArgoCD Vault Plugin Spike#2914
Implement RBAC for `svc-bie-kafka` in our pre-prod environment#2916

For Bianca: 
1. FY23 Q2 Partner Team Survey: Develop Narrative
abd-vro #2874
2. Develop proposal for maturing our Partner Team Engagement
abd-vro #2860
