### ISSUE TITLE
Complete Alembic Setup for CC Team Use

### ISSUE THREAD

**Issue by nelsestu** [department-of-veterans-affairs/abd-vro#2886]
As a VRO platform developer, my goal is to empower partner teams in handling their data migrations independently. 
Originally the work for Alembic Credential setup was done in #2329, but there are parts missing and work required to roll it out to each environment.

Acceptance Criteria
1. The following criteria should hold for both local and LHDI environments:
2. A new Postgres schema is created for use by the CC team
3. A new DB user with superuser privileges only for the schema from 1 is created with credentials propagated stored in HashiCorp vault and propagated to the K8s cluster.
4. References for these credentials are communicated to the CC team, including context on the expectation that CC owns it from here. The CC Team has asked for a pairing session for this.
5. Documentation is created for this offering from a VRO perspective under partner team documentation in the wiki - https://github.com/department-of-veterans-affairs/abd-vro/wiki

Notes about work
To complete this work, an engineer will need to log into the RDS postgres instance in each of our LHDI environments and use psql to manipulate the instances to satisfy the AC. This can be done by creating a shell into one of the running pods in the cluster namespace, installing psql as a CLI tool if necessary, and issuing the proper psql commands.

**Task list- please check off as you complete them**

- [x] 1. ~Use dev-tools pod to login with psql and create a new DB user and postgres schema for CC team~ the original assignee had included this manual step in the task list they created, however this is not what we want and misses the purpose of flyway, our database migration tool.  Instead of leaving this to be a manual process performed during deployment by someone who both remembers to do it, and how to do it, we want to automate this step using a flyway migration script.  That way, when the script gets deployed, the requirements we've verified in this ticket will be applied to what ever environment was just deployed.
- [ ] 1. Create a flyway migration script that gets invoked automatically just like any other database migration process.  The script will use flyways placeholder feature to support passing the values in from vault.  This suggests that this subtask will have the following configuration elements:
  - [ ] a. pass the username, password and schema name of the domain-cc postgres user in as flyway placeholder environment variables into the db-init helm chart.  These config settings will need to be populated via Kubernetes secret.  Once we have argocd in place, these kubernetes secrets will populate automatically from vault.  In the meantime creating the secrets with the correct values will be handed as a bash script as described in the next bullet point.
  - [ ] b. pass the username, password and schema name of the domain-cc postgres user in as environment variables to the domain-cc service.  This time the intended recipient is the CC team, where they will then be able to run alembic commands using the values passed via these environment variables.
- [ ] 2. add username and password to Vault, for the postgres user described above.  Adding things to vault is a fully manual process at this time.  There is a cli client and automation is something to consider in the future.
- [ ] 3. add the username and password as a domain-cc-db kubernetes secret.  While this was done manually, here again we want to avoid manual steps when possible, and will therefore create a script and include the usage of the script in the documentation mentioned.
- [x] 3. Give secret refs to CC team - the team is now just waiting on VRO to provide these in other environments.
- [ ] 4. dev was completed manually by the original issue assignee.  revisiting this issue for other environments highlights the manual steps and why they are so problematic.  In addition to repeating the setup for all envs, we will complete the work by automating the manual steps.
- [ ] 5. Update documentation

new documenation-https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-Partner-Team-Database-Migrations

**Comment by nelsestu** [comment]
This work got hung up with some failing integration tests. It is hard to tell which thing fixed it, whether passage of time eventually cleared the github action cache, or whether rebundling the branch with a squash merge forced the cache refresh.  The branches approval and merge to develop was confirmed with the CC team here: https://dsva.slack.com/archives/C01Q7979Z7D/p1714493901624459?thread_ts=1711990256.657119&cid=C01Q7979Z7D

**Comment by meganhicks** [comment]
Hey @tejans24 you documented Alembic right? Where is it?
