### ISSUE TITLE
Staging Review Support

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#2892]
This ticket tracks what we need to do for the [staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) process.

The product manager completes the Before Meeting/VFS Actions in the Staging Review section of their [collaboration cycle ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff). They schedule the meeting with a 4 day lead time and do this once their product meets the following requirements:
- All test scenarios must be able to be completed by the Governance team.
- All possible user paths must be included for testing.
- Any test users identified for the product must be available, valid, and/or functioning as specified. We will make no exceptions for third-party dependencies.
- All known bugs that could cause false errors have been addressed.

VFS Product Manager invites:
   -  Product manager
   - OCTO-DE Product lead
   - Anyone else from your team who significantly contributed to the artifacts
   - CAIA and QA specialists
   -  Other VA stakeholders

Platform participants:
   -  Design
   -  Accessibility
   -  Content
   -  IA
   -  QA
   -  Product
   -  OCTO-DE practice area leads

## Notes about this work
- Artifacts should be provided to reviewers at least 4 days before the scheduled meeting/review
- A VFS team that launches a static page through the Collaboration Cycle will not be held responsible for upholding the QA Standards. Static pages do not have dynamic content that requires extensive testing.
- Review this [support documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket) for more information

## What to expect from the Governance Team
- Accessibility, Design, Content, and IA findings will be documented in issue-focused tickets, based on the [VA.gov experience standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html). Critical issues will have the launch-blocking label and must be addressed prior to launch.
- Any Accessibility issues that are not addressed prior to launch must be communicated to the VA 508 Office via [Audit Request.](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest) This is the responsibility of the VFS team.
- QA findings will be reported in one ticket that documents whether each QA Standard has been met.

Outcomes 
- Governance team will update any issues in the collaboration cycle ticket
- CAIA team will create their own tickets to track issues
 
## Artifacts Needed
```[tasklist]
### Tasks
- [x] **Product artifact**: Staging URL, test user information, and tasks are stored in a .md file in the va.gov-team-sensitive repository
- [ ] **QA artifact**: [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) --> https://github.com/department-of-veterans-affairs/abd-vro/issues/3052
- [x] **Accessibility artifact**: [Accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Submit Staging Review request
```

**Comment by mackhowell-nava** [comment]
Collab cycle ticket for MVP: https://github.com/department-of-veterans-affairs/va.gov-team/issues/62491
Collab cycle ticket for this launch: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69299
Duplicate of this ticket? https://github.com/department-of-veterans-affairs/abd-vro/issues/2551

**Comment by dfitchett** [comment]
Couple notes about QA Artifacts:
* [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports):
  * > This is the percent of the initiative’s user stories are covered by tests in the Test Plan. This can be reported as a chart, a table, or simply a number. 
  * I'm not sure our stories were always framed as "user stories", but the compilation of our user stories come down to the effort as whole. Therefore, I'd say 100% of them were connected to being able to show this education to the user if they have a disability rated at the maximum rating.   
* [Summary (Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports):
  * > demonstrate what percent of defects uncovered during testing were uncovered by executing tests in the Test Plan as well as which defects are resolved or outstanding. This can be reported as a chart, a table, or simply a number.
  * We will have to compile the list any defects found during testing. Cheers 🥂 to hoping for zero 🤞 
* [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation)
  * We do not have any specific e2e tests for max ratings API
  * We are only really only modifying the front-end display of data fetched from the backend call to the max ratings api. It is a minimal change in front-end behavior of the disability-benefits/all-claims application (specifically only the rated disabilities page of the 526), and it's base functionality already has cypress [e2e tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims/tests) present. So I believe additional e2e tests are not necessary, and the change in behavior is well tested via unit tests.
* [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage):
  * Unit test for front-end [here](https://github.com/department-of-veterans-affairs/vets-website/blob/7223facfd15a2beb191d46fa6264f5411d7dee3a/src/applications/disability-benefits/all-claims/tests/pages/ratedDisabilities.unit.spec.jsx#11) and the coverage report for the [Disability-benefits/all-claims ](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)
  * Unit tests for back-end can be found from results of Github Action for latest [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16746) related to max-cfi shows the files relating to max-cfi / claim fast tracking have greater than 80% code coverage:
![code_coverage_nanotone:track-cfi-on-526submissions](https://github.com/department-of-veterans-affairs/abd-vro/assets/135860892/94b22aba-3d82-4034-aaf6-459d0e8dab8d)

Additionally, according to these [docs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-QAartifacts*), the traceability reports Coverage for references and Summary Defects are not required.

**Comment by mackhowell-nava** [comment]
Updated the staging review section of the collaboration cycle ticket directly: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69299

Note: After my meeting with Shira last week, we realized that many of the official docs are not needed in this case (Content, IA, QA), due to the small scope of our changes within the larger 526 product. For the QA section, I did the above notes from Derek directly in the "staging review" section of the ticket. Going to close out this ticket now!
