### ISSUE TITLE
Sprint U

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2925]
#### Ujung Kulon National Park, Indonesia

<img src="https://static.wikia.nocookie.net/naturerules1/images/1/14/Javan-rhinoceros-in-shallows-of-river.jpeg/" width='300'/><img src='https://upload.wikimedia.org/wikipedia/commons/a/a4/Babi_hutan_lagi_cari_makan_siang_di_pulau_peucang_yang_berada_di_Taman_nasional_ujung_kulon%2C_Jawa_Barat.jpg' width='300'/>
<img src='https://upload.wikimedia.org/wikipedia/commons/b/b0/Kelomang%2C_Cibunar%2C_Taman_Nasional_Ujung_Kulon%2C_11082014.jpg' width='300'/><img src='https://www.naturalworldheritagesites.org/wp-content/uploads/2021/07/Ujung-Kulon-National-Park-Location-Map.jpg' width='300'/>
Images of a javan rhinoceros, wild boar, and hermit crab living in the park; and a map showing the park's location on the south-west tip of the island of Java.

<details>

<summary>Fun Facts:</summary>

- located on the island of Java in the province of Banten, Indonesia. Ujung Kulon ([pronunciation](https://forvo.com/word/ujung_kulon/ )) itself means Western End or Point West in Bantanese. 
- ~475 square miles, a remote area of low hills and plateaus
- best known as the last refuge of the one-horned Javan rhinoceros; fewer than 60 remain alive, although they once thrived throughout the islands of Java, Borneo, and other areas of Southeast Asia
- other species in the park include bantengs (a type of wild cattle), muntjacs (barking deer), and green peafowl.
- more info: [Taman Nasional Ujung Kulon](https://tnujungkulon.menlhk.go.id/) , [wikipedia](https://en.wikipedia.org/wiki/Ujung_Kulon_National_Park) 
</details>

## Team Capacity: 
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. _**Note: includes time off, non-sprint commitments, and new team member ramp-up.**_
All Eng: 81.4%
All UX: 85.7%
All VRO Team: 82%

## Sprint Goal: 
_What do we want to have accomplished by the end of this sprint?_
1. Help partner teams and VA stakeholders:
-- Complete CC Requests, which have been pending for some time due to RBAC work causing delays
-- Assist Enablement Team with PIA
2. Improve deployment 
-- Determine a plan for deployments
3. Mature the platform
-- Set up PagerDuty for the team. 
4. Data visbility
-- Review past Data Visibility initiatives and utilize findings to formulate a set of interview questions for prospective partner teams regarding their data requirements.

### Top Priority (work on these first):
- [x] Review PIA-due 5/9 #2944
- [x] Investigate why CC Application Went Down #2883
- [ ] Add ActorUserId field to RDS database #2724
- [ ] Begin tracking description for ContentionAssociatedToClaim, ContentionDeleted, #2810

### Other Sprint Commitments in Priority Order (work on these if top priority are done/handled):
Devs:
- [x] On call Primary and Secondary #2927
- [x] Team work: Workshop how we will improve deployments #2955 (so that DORA metrics can be easily captured) 
- [x] Tech spec: Develop an incident response plan #2570
- [ ] Discovery on creating a data storage retention policy for the VRO platform #2823 (In Progress - will carry over into Sprint V)
- [x] Discovery: Ensure graceful transition when k8s pods are evicted #2816
- [ ] Discovery: Integration tests during deployments to LHDI #2579
- [x] Audit documentation included in the VRO wiki #1530
- [ ] Create an oncall rotation and process for engineers in Pager Duty #2445 (Blocked - Berni can help Teja get LHDI admin/s to help us with permissions issues on PagerDuty settings)

UX: 
- [ ] Data Visibility Revival: Synthesize previous and develop discussion guide #2917
- [ ] Data Visibility Revival: Create Coverage Plan (for EE designer/researcher backfill) #2993
- [x] Update Design/Research Roadmap #2992

### Unplanned (these were added after Sprint Planning):
- [x] Deployment of CC change to Prod #2977
- [ ] Implement RBAC for svc-bie-kafka in our prod environment #2560 (BLOCKED)
