### ISSUE TITLE
Sprint V

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2926]
# Voyageurs National Park 
International Falls, Minnesota 

<img src="https://www.nps.gov/voya/learn/nature/images/Voyageurs-IntlDarkSkyPark-Logo_600px_1.png" width=200/><img src="https://github.com/department-of-veterans-affairs/abd-vro/assets/943046/d6817bbc-5fa8-4f6c-a34b-c479f3792d4e" width=250/> 

[Voyageurs National Park](https://www.nps.gov/voya/index.htm) is 214k acres of boreal and northern hardwood forest.
- by car: 5 hours north of Minneapolis; 4 hours south from Winnipeg, Manitoba.  by airplane: Minneapolis-St.Paul (MSP) (5 hours); Falls International Airport (INL) (20 minutes)
- designated an [International Dark](https://darksky.org/what-we-do/international-dark-sky-places/all-places/) [Sky Park](https://www.nps.gov/voya/learn/nature/dark-sky-park-designation.htm ) and hosts  stargazing programs throughout the year.
- according to the [Voyageurs Conservancy](https://www.voyageurs.org/darkskies): 
  - approximately 80% of North Americans are unable to see the Milky Way due to light pollution. 
  - nocturnal animals, like red foxes, depend on dark sky preservation for healthy predation habits.
  - light pollution impacts [sea turtle populations](https://www.darksky.org/our-work/sea-turtle-conservation/). Baby sea turtles hatch on land and find the ocean by identifying its bright horizon. Artificial light from homes and businesses near coastline, however, confuses hatchlings and can cause them to go in the opposite direction. ([ref](https://www.outdoors.org/resources/amc-outdoors/conservation-and-climate/what-is-a-dark-sky/))
  
## Capacity: 
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. _**Note: includes time off, non-sprint commitments, and new team member ramp-up.**_
- All Eng: 58.2%
- All UX: [%] (Bianca is OOO 5/20-5/24, but we're borrowing EE UX team members to help out this sprint with Data Visbility -- that capacity will be reflected on EE team's sprint plan).
- All Team: 50.9%

### Are there any tickets that will carry over from previous sprint?
- Discovery on creating a data storage retention policy for the VRO platform #2823

- [x] - #2445 (Blocked)
- [x] - #2579 (Product Acceptance)
- [x] - #1530 (Product Acceptance)
- [ ] - #2724 (Code Review)
- [ ] - #2810 (Code Review)
- [ ] - #2975 (In Progress)
- [ ] - #2943 (In Progress)

## Sprint Goal: 
What do we want to have accomplished by the end of this sprint?

Formulate an understanding of the root causes behind application downtime, propose supplementary monitoring measures for BGS and BIP and execute the implementation of these measures. 

### Top Priority (work on these first)

- [ ] (2) Application monitoring for BIP #2932 
- [ ] (2) Implement custom monitoring for BGS #2980
- [x] (2) Deployment for the CC Team #2991
- [x] (2) Deployment for EE team by May 28th #3007 _Note from Berni to Megan: This deployment is to support EE's Max CFI phased launch. I've added it here because there's an upcoming deadline. Let's chat if you have questions.)_

### Help our partners and VA Stakeholders
- [x] (1) Partner Team Deployment guide for higher environments #2982
- [ ] 
### Mature Platform
- None

### Improve Deployment
- Need ticket to coordinate meeting with LHDI and VRO team to discuss ArgoCD migration (Lisa / Erik)

### Other Ongoing Work (security & compliance; documentation; etc.)
- [ ] Onboard Kyle Brost #3006

#### Who is On Call? 
Primary: Mason
Secondary: Lisa
- [x] (3) https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/3008

### Data Visibility
Design/Research: (Christine from EE team helping out)
- [ ]  Data Visibility Revival: Set up data collection and schedule interviews #2953

**Comment by BerniXiongA6** [comment]
Hi @amylai-va -- since I helped out with Sprint Planning and Backlog refinement while @meganhicks was out for a few days, I wanted to bring to your attention the Sprint Plan we've come up with for VRO's Sprint V. The Top Priorities will focus on supporting our Partner Teams' deployments, and to create application monitoring for BIP and BGS. There a few tickets this sprint that our team will refine tomorrow. Please let Megan or me know if you have any questions or whether this plan looks OK to you!

**Comment by BerniXiongA6** [comment]
Hey @ChristineRoseSteiffer -- this is an FYI for you regarding the Data Visibility work that you've kindly offered to be backfilling for Bianca in Sprint V. I've included Bianca's tickets above on this Sprint V epic, but if you need to work off of a respective EE ticket that you create on EE board, I think that's reasonable. I'll make sure to align those EE and VRO tickets when it comes time for Sprint Review and Monthly reporting. You can tag @meganhicks and me on your tickets so we can follow along this sprint. Let us know if you have any questions. Thanks again!

**Comment by amylai-va** [comment]
Thanks @BerniXiongA6! FYI @jstrothman @CorySohrakoffUSDS, here are VRO's sprint goals for visibility
