### ISSUE TITLE
Sprint W

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2972]
# National Monument
Walnut Canyon  
<img width="853" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1nQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98c51e326910e89bf469fca0f3d034f05f1ed108/image.png" alt="image.png" />

- Ancient Cliff Dwellings: The Sinagua people built the cliff dwellings in Walnut Canyon around 1100 to 1250 AD. These structures were ingeniously constructed within the natural alcoves of the canyon walls.
- Sinagua Culture: The name "Sinagua" is derived from the Spanish words "sin agua," meaning "without water," reflecting the arid conditions in which these ancient people thrived.
- Biodiversity: Walnut Canyon is home to a unique combination of desert and forest ecosystems. Visitors can see a variety of plant species, including ponderosa pines, pinyon pines, junipers, and various cacti.

## Capacity: 
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. _**Note: includes time off, non-sprint commitments, and new team member ramp-up.**_
- All Eng: 55.1%
- All UX: 77.1%
- All Team: 57.9%
- Time off : Erik is off starting on 6.12- and will be off for 2 weeks. Ponnia is off wed-monday this week, Megan is off tomorrow and Friday and the 13th and 14th. 

### Are there any tickets that will carry over from previous sprint?
 - [x] #2724 (Code Review) - Rolling 2 Sprints 
 - [x] #2810 (Code Review)- Rolling 2 Sprints 
 - [x] #2975 (In Progress) - Rolling 3 Sprints
 - [ ] #2943 (In Progress)- Rolling 3 Sprints 
 - [ ] Application monitoring for BIP #2932 (In Progress) 1 Sprint
 - [ ] Implement custom monitoring for BGS #2980 (In Progress) 1 Sprint 

## Sprint Goal: 
What do we want to have accomplished by the end of this sprint?

Primary: Support Bianca in new product research by assisting with interviews and taking notes as needed.
Secondary: Finish setting up monitoring for BIP and BGS and finish work in progress 
Ensure ArgoCD functions correctly for the BIP service to facilitate its implementation for other services and enhance our deployment process.

### Top Priority (work on these first)
- [ ] Data Visibility Revival: Conduct interviews, synthesize data, and develop readout #3002 3
- [x] Resolve ArgoCD sync issues on svc-bip-api  #3030 3

## Other Sprint Commitments in Priority Order (work on these if top priority are done/handled):
- [x] VRO pitch deck #3061- Megan will lead this effort

### Documentation Clean Up
- [x] Update engineering onboarding docs #3023

#### Who is On Call? 
- [x] On call Primary and Secondary #3013 

## Unplanned Work (these tickets were added post-Sprint Planning)

- [ ] Onboard Paul Baumann #3070
