### ISSUE TITLE
Sprint X

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3016]
# National Park
  
## Capacity: 
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. _**Note: includes time off, non-sprint commitments, and new team member ramp-up.**_
- All Eng: 48.1%
- All UX: 68.6%
- All Team: 51%

### Are there any tickets that will carry over from previous sprint?
- [x] #2943 (In Progress)- Rolling 4 Sprints
- [x] Application monitoring for BIP #2932 (In Progress) 2 Sprints
- [ ] Implement custom monitoring for BGS #2980 (In Progress) 2 Sprints 
- [x] Data Visibility Revival: Conduct interviews, synthesize data, and develop readout #3002 1 Sprint
- [ ] Onboard Paul Baumann #3070

## Sprint Goal: 
What do we want to have accomplished by the end of this sprint?

-	Determine next steps on Data Visibility Work 

### Top Priority (work on these first)

Reduce capacity to workshop the next product facing project we will take on for the portfolio 
- After Sprint Planning, we realized that we will be working with a smaller team in the upcoming Sprint since Mason and Erik will be off. Additionally, we have Paul starting with us. As a result, you'll notice a section in this Sprint Epic titled "If we have more capacity." The tickets in this section are listed in priority order and can be pulled as capacity allows.

### Help our partners and VA Stakeholders
- [x] [Request]: Production release of develop for cc-app #3074 

### Mature Platform
- [ ] Enhance the Incident Response Plan -Comms Standards #3015 
- [ ] Top Use Cases: Incident Reports - Research and Ideation #2837

### Improve Deployment
- [x] Set up scheduled SecRel job #3031

#### Who is On Call? 
- [ ] On call Primary and Secondary #3020

### Data Visibility 
- [x] Conduct interviews, synthesize data, and develop readout #3002
- [x] Ideation Workshop & Next Steps #3101

## If we have time 

- [ ] Configure ArgoCD + Vault for svc-bip-api #3037
- [ ] Containerize Integration Tests for BGS #2999 
- [ ] Implement an RDS retention and storage policy #2116
- [ ] Implement custom monitoring for BIE abd-vro #2981 
- [ ] Implement DLQ for RabbitMQ Messages #2758
