### ISSUE TITLE
Update the Rating Schedule for the Digestive System

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3028]
## Summary
- The Rating Schedule has been updated for the digestive system.
- Since our max ratings are tied to each diagnostic code, we have to update the max ratings API and the spreadsheet that powers it.
- Since we're scheduled to roll out the max CFI intervention for all conditions to the first 10% of users on May 28th -- **_we want to figure out if this will push that date back_**.
- Question: Does this affect the hyphenation logic? 
- See the tasks below...

## Details 
From the relevant [Slack message from Josh here](https://dsva.slack.com/archives/C01BVF2A3V0/p1716320170262719):

> **Background**
> On **March 20, 2024**, Compensation Service’s Digestive System Final Rule was published to the Federal Register with an effective date of **May 19, 2024**. While systems and Disability Benefits Questionnaires (DBQs) have been updated, the Federal Register will not incorporate the regulatory revisions in the Schedule of Ratings for the Digestive Body System ([38 CFR 4.114](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-4%2Fsubpart-B%2Fsubject-group-ECFR52ba1b312b58845%2Fsection-4.114&data=05%7C02%7C%7C30423e0e591b4eb6021208dc79b32b35%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638519057668778970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=2YuOHWt3AXLzSEWz8KXDdUzFp1ssNjV15xLtpM%2BpHYc%3D&reserved=0)) until a few days after May 20, 2024.
>
> **What is changing and when?**
> The Digestive Body System portion of the Rating Schedule effective **May 19, 2024**. Please see the attached document titled Revised 38 CFR 4.114 Schedule of Ratings for the Digestive System for all sections and items that have been updated.
>
> **What is not changing?**
> All other body systems in the VA Rating Schedule are not relevant to this update and will not be affected.
> 
>
> **Where is it changing?**
> The updates will occur to 38 CFR § 4.110 - §4.114.
> [38 CFR 4.110 Ulcers](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-4%2Fsubpart-B%2Fsubject-group-ECFR52ba1b312b58845%2Fsection-4.110&data=05%7C02%7C%7C30423e0e591b4eb6021208dc79b32b35%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638519057668784908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Pm64%2B0lCVm9jhN8Fig6OH23GkFfsf6TniGrQwuSxAy0%3D&reserved=0)
> [38 CFR 4.111 Post Gastrectomy Syndromes](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-4%2Fsubpart-B%2Fsubject-group-ECFR52ba1b312b58845%2Fsection-4.111&data=05%7C02%7C%7C30423e0e591b4eb6021208dc79b32b35%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638519057668790555%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=fqcAVM9nmD46p6GuG2DG6NY6Q%2F%2F4xBgrhmoPAQ9x0kk%3D&reserved=0)
> [38 CFR 4.112 Weight Loss](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-4%2Fsubpart-B%2Fsubject-group-ECFR52ba1b312b58845%2Fsection-4.112&data=05%7C02%7C%7C30423e0e591b4eb6021208dc79b32b35%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638519057668796260%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=9qSKiywGkDwGMDPZ6sIaqzEr2lZX44H3tejk6sswCgA%3D&reserved=0)
> [38 CFR 4.114 Schedule of Rating - Digestive System](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ecfr.gov%2Fcurrent%2Ftitle-38%2Fchapter-I%2Fpart-4%2Fsubpart-B%2Fsubject-group-ECFR52ba1b312b58845%2Fsection-4.114&data=05%7C02%7C%7C30423e0e591b4eb6021208dc79b32b35%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638519057668801875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=NhHui8uo3jj%2BLFs87rDm7UHnvGC4Uxn%2FB%2FS9CG9eh1M%3D&reserved=0) 
> 
> **Why is it changing?**
> The VA revised this portion of the Digestive Body System of the Rating Schedule due to recent advances in medical technology and treatments that were not accounted for since the last revision.
> 
> **What else do I need to know?**
> **On or around May 23, 2024**, the eCFR will be updated to reflect the updates made to the Digestive Body System portion of the Rating Schedule. Once the eCFR is appropriately updated this email and its attachments will no longer need to be referenced for regulatory guidance.
>
> **IMPORTANT:**
> To mitigate any adjudication errors and/or delays in processing claims involving digestive conditions, please provide all Rating Veteran Service Representatives (RVSRs), Rating Quality Review Specialists (RQRSs), Decision Review Officers (DROs), etc., with the attached “hard copy” of the revised 38 CFR § 4.114 Schedule of Ratings for the Digestive System as soon as possible. Changes are highlighted in yellow.
> 
> 

```[tasklist]
### Tasks
- [x] Create a new sheet/tab with just the digestive system, and update it accordingly
- [x] Send NVBA (the compensation services) our new digestive system sheet for feedback (Mack sent email on June 17th)
- [x] ~~Incorporate feedback into our master spreadsheet~~ (can create a follow up ticket for this when we get a response back...
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3047
- [x] Determine if the above steps would push back our May 28th 10% launch
```
