### ISSUE TITLE
Research planning support for VRO

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/abd-vro#3034]
```[tasklist]
### Tasks
- [x] Go through Bianca's ticket and complete all needed steps #2953
- [x] All work that is developed should be uploaded to this Google Drive [Data collection folder](https://drive.google.com/drive/folders/1uYKVjR-LEQ6hUyhb18zAEnUpT9LF9B5-?usp=drive_link).
```
```[tasklist]
### Tasks for [Interview Guide](https://docs.google.com/document/d/1fsagewNUKpqxMMRXXLjjr2RYVc2XKOmaq5Vgjy1AlFs/edit) (for facilitator)
- [x] Develop ‘cheat sheet’ section in interview guide for EE Team
- [x] Make 6 copies of the interview guide and rename each with corresponding team name
- [x] Move interview guides to respective folder in Google Drive
- [x] Draft consent language for recording - For Reference: [Nava Interview Guide Template](https://docs.google.com/document/d/10luIAE9mlQY1caquHLSsoAxlo9oUXd6BuxKgmxUOZuc/edit#heading=h.207yogsn65ua), [Consent Guidelines](https://navasage.atlassian.net/wiki/spaces/NH/pages/422215896/Playbook+Asking+for+consent)
```

```[tasklist]
### Tasks for Note-taking template
- [x] Develop separate note-taking docs for each interview
- [x] Copy questions from Interview Guide
- [x] Create ‘Key Takeaways’ section
- [x] Move each doc to respective folder in Google Drive
```
```[tasklist]
### Tasks for [Data Collection](https://drive.google.com/drive/folders/1pXmcfdTt2CvypjAB_S-LXVNsQ-RU9NRD)
- [x] Create additional folder structure and naming convention
- [x] Checklist for each team’s folder:
- [x] Interview Guide
- [x] Note-taking Template
```

**Comment by ChristineRoseSteiffer** [comment]
Bianca is cutting her trip short, so some of these tasks may move back onto her plate. Just FYI @mackhowell-nava @BerniXiongA6

**Comment by ChristineRoseSteiffer** [comment]
All tasks our team completed are recorded in this ticket. Further support in future sprints for notetaking might be needed. Closing this ticket as done :)

**Comment by BerniXiongA6** [comment]
You're the best, thanks @ChristineRoseSteiffer !

**Comment by bianca-rivera** [comment]
Made a minor correction that the ticket that should be referenced is #2953 instead of #2917, in terms of capturing the work Christine helped with during Sprint V for the week of 5/20-5/24.

**Comment by BerniXiongA6** [comment]
Thanks @bianca-rivera that was my bad with referencing the ticket number originally.
