### ISSUE TITLE
Sprint Y

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3050]
**Yosemite National Park**
<img width="618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1qQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d157741c2d7faf51b92814bed9f34f36f7f3798a/image.png" alt="image.png" />

<img width="595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f02793393ccae7e3df66d9e8fabaf39782bc2b52/image.png" alt="image.png" />

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 62.1%
All UX: 90%
All Team: 65.6%

(Team capacity for Sprint Y is 15.8 points)

## Carryover from Previous Sprint
Are there any tickets that will carry over from previous sprint?
- [x] Implement custom monitoring for BGS #2980 - code review 
- [x] Onboard Paul Baumann #3070 - sprint ready 
- [ ] Enhance the Incident Response Plan -Comms Standards #3015 - in progress 
- [x] Additional work from on call #3143

# Sprint Plan
## Sprint Goal:
What do we want to have accomplished by the end of this sprint?
- [x] Continue solutioning Data Visbility #3185 
- [x] Continue implementing ArgoCD across VRO services (ArgoCD Tickets will always be labeled ArgoCD and be in improving deployments, - Configure ArgoCD for svc-bie-kafka #3086 and Configure ArgoCD for domain-xample #3091
- [X] Finish custom monitoring #2980 

### Data Visibility
- [x] Workshop data visibility solution ideas #3185

### Help our partners and VA Stakeholders
- [x] Top Use Cases: Incident Reports - Research and Ideation #2837 
- [x] Top Use Cases: Incident Reports - Launch & Comms #3081

### Monitoring and Alerting
- [ ] Assess health checks- follow up for BGS app going down #3144

### Improve Deployment
- [x] Containerize Integration Tests for BGS #2999
- [x] Configure ArgoCD for svc-bie-kafka #3086
- [x] Configure ArgoCD for domain-xample #3091
- [x] Implement a Deployment Policy #2976

### Who is On Call?
- [ ] On call Primary and Secondary #3140

### Stretch goal - if we have time
- [ ] Implement custom monitoring for BIE #2981

# Unplanned Work (these tickets were added post-Sprint Planning)
- [ ] Incident Reported: RabbitMQ is processing messages with no TTL #3181
- [ ] Implement DLQ for RabbitMQ Messages #2758
- [x] Implement RBAC for `svc-bie-kafka` in our prod environment #2560
