### ISSUE TITLE
Sprint Z

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3099]
**Zion National Park**
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61d202c47549c27306b2cd9ac7312fb29f93e558/IMG_5800.jpg" alt="IMG_5800.jpg" />
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9qQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0506e4a516e4b1659ba246fc27c3101f132485a6/IMG_5362.jpg" alt="IMG_5362.jpg" />

# Capacity
The percentages
 below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

**All Eng: 88.5%
All UX: 92.9%
All Team: 89%
(Team capacity for Sprint Z is 21.4 points)**

**Capacity notes from Berni:** 
- Time off: Mason's possible jury duty on 7/29
- Paul off 7/19
- Cheng will miss a day
- % Working on Sprint  Commitments: I've adjusted everyone's percentage this sprint to 65% (default is usually 70%) given what I know about all the working sessions and meetings scheduled for VRO team members -- with the exception of Paul (50%) as he continues to ramp up.

## Carryover from Previous Sprint
Are there any tickets that will carry over from previous sprint?
- [x] Incident Reported: RabbitMQ is processing messages with no TTL #3181
- [ ] Implement DLQ for RabbitMQ Messages #2758
- [x] Verify BIP UAT credentials #3178
- [ ] assess health checks- follow up for BGS app going down #3144
- [x] Remove camel code in xample-workflow app #2745
- [x] Top Use Cases: Incident Reports - Launch & Comms #3081
- [x] Implement custom monitoring for BIE and xample-workflow #2981
- [x] Enhance the Incident Response Plan -Comms Standards#3015
- [x] On call Documentation and Deployment Policy #2976

# Sprint Plan
## Sprint Goal: 
What do we want to have accomplished by the end of this sprint?
- [ ] Finish Implementing Argo on all internal services 

### Improving Partner Team Experience
**Top Use Cases: Deployment Requests**
- [x] Research and Ideation #2672
- [ ] Align and finalize all Incident Response documentation #3199
- ~~Prototype, Launch, and Comms #2795~~ (moved to Sprint A instead)

### Keep the platform running
- [ ] On call Documentation #3123
- [ ] Align and finalize all Incident Response documentation #3199

### Partner Team Requests
- [ ] The CC Team has notified us that they will have a deployment request towards the end of the Sprint. 
- [x] Deploy ActorID and Description to Prod #2984

### Monitoring and Alerting 
- [ ] 

### Incidents
- [ ] 

### Improve Deployment
- [x] Configure ArgoCD for svc-bgs-api #3087
- [ ] Configure ArgoCD for dev-tools #3088
- [x] Configure ArgoCD for rabbitmq #3090
- [ ] Configure ArgoCD for db-init #3089

###Stretch goal Partner Team services 
- [ ] Configure ArgoCD for Contention Classification (CC) #3092
- [ ] Configure ArgoCD for EP Merge (EE) #3093
- [ ] Configure ArgoCD for Max CFI (EE) #3094

### On call
Who is On Call?
- [ ] On call Primary and Secondary #3188

# Demo Plan
**What could we demo?** 
- Demo all the apps in ArgoCD (next sprint)
- POC for deployment and feature requests (next sprint)
- Incident Response updates (Bianca)
- On call documentation (Kyle)

# Unplanned Work (these tickets were added post-Sprint Planning)
- [X] Other SecRel Vulnerabilities Carrying Over from Sprint #3203 
- [X] Setuptools Vulnerability Failing SecRel in VRO Python Projects #3201
