### ISSUE TITLE
Sprint A

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3100]
<a href="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Alpaca_in_the_Toledo_Zoo.jpg/640px-Alpaca_in_the_Toledo_Zoo.jpg" target="_blank">
<img alt='Alpaca_in_the_Toledo_Zoo' src='https://github.com/user-attachments/assets/f301f786-1c0e-4d59-9481-75085369b5b5' width='300'></a> 
<details>
 <summary>Alpaca fun facts</summary>

Alpacas are part of the camel family. 

[How to choose your first alpaca](https://mauialpaca.com/how-to-chose-your-first-alpaca): 
* alpacas are herd animals and very socially oriented
* if you are interested in female alpacas, you should get three or more
* if you start with males, you should get two or more
* male and female alpacas cannot share the same fenceline because fighting between them will occur
* *Alpacas vs llamas*: alpacas are typically shy and polite, and are more comfortable in herds. Llamas are more confident and brave, and are solitary animals. Alpacas are smaller. Alpacas have shaggy hair that is used for fleece production. Llamas’ hair is coarser, and their wool is considered inferior. 
<img src='https://twpark.com/wp-content/uploads/2022/10/llama-alpaca-size_large.webp' alt="difference between alpacas and llamas" width='500'/>

* Alpacas have an exceptionally unique immune system. see: "Meet the alpacas that are helping researchers who study autism, Alzheimer’s and cancer" [Vanderbilt](https://news.vanderbilt.edu/2019/08/13/meet-the-alpacas-that-could-cure-autism-alzheimers-and-cancer).

Google: [alpaca ranch near me](https://www.google.com/search?q=alpaca+ranch+near+me)

</details>
---

# Capacity
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 86.2%
All UX: 46.4%
All Team: 81.3%
(Total points VRO team can handle this sprint: 19.5)

## Carryover from Previous Sprint
Are there any tickets that will carry over from previous sprint?
- [x] Create demo materials for Incident Report workflow #3218
- [x] Align and finalize all Incident Response documentation #3199
- [ ] assess health checks- follow up for BGS app going down #3144
- [x] Configure ArgoCD for db-init #3089
- [x] Configure ArgoCD for dev-tools #3088

# Sprint Plan

## Sprint Goal:
1. Finish Implementing Argo on all partner services, overcommunicate the changes and demo the new deployment guide for lower environments. 

### Improve the Partner Team Experience
- [x] Top Use Cases: Deployment Requests - Prototype, Launch, and Comms #2795
### Metrics
- [x] Define mean time to resolve an incident (mean time to resolve, MTTR) #3191

### Keep the Platform Running
- [x] Update Secrel documentation #3022
- ~~Automate RDS DbInstance Initialization Steps #2004 (moved to Sprint C)~~

### Partner Team Requests
- [ ] Enhancement to help EP Merge metrics #3213
- [ ] DLQ ticket #3238

### Monitoring and Alerting
- [ ] Custom Monitoring for Rabbit MQ and K8s termination grace period #2817
- [ ] Monitoring Standards for VRO #2968 - this would be a stretch goal

### Incidents
- list here if any

### Improve Deployment
- [ ]  Configure ArgoCD for Contention Classification (CC) #3092
- [x]  Configure ArgoCD for EP Merge (EE) #3093
- [x]  Configure ArgoCD for Max CFI (EE) #3094
- [ ]  ArgoCD final steps for partners #3176

### On call
Who is On Call?
- [x] On call Primary and Secondary #3246

## Demo Plan
What could we demo?
- list here if any ideas 

# Unplanned Work (these tickets were added post-Sprint Planning)
- Add Dead Letter Queue and update existing queue configurations to use it #3238
