### ISSUE TITLE
follow-ups from 7/1/2024 incident 

### ISSUE THREAD

**Issue by lisac** [department-of-veterans-affairs/abd-vro#3143]
## tasks
- [x] write up (shorter) incident report - Lisa : [Partner Team Incident Reports](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Partner-Team-Incident-Reports)
- [x] write up (longer) post mortem (due to Sev 1 incident) - lisa : [Post-incident reviews](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Post%E2%80%90incident-reviews)
- [x] deploy `svc-bgs-api` for enhanced monitoring - lisa 
- [ ] ~deploy VRO apps that are likely to have images whose SecRel signatures are no longer valid~ _invalid, due to new information; follow-up work in #3183_

**Comment by BerniXiongA6** [comment]
@nelsestu would you comment here and let us know when you have the new ticket spun up for the fourth bullet point? I'd like to add this to the mid-sprint progress metrics I'm working on. Thank you so much! cc: @lisac @meganhicks

**Comment by lisac** [comment]
update: the 4th item was on the assumption that image signatures expire on the span of weeks, and that we'd then be able to run deployments accordingly (deploy whatever was last deployed more than [x] weeks ago). 
in asking LHDI this week about the expiration, it appears my assumption is flawed. Still tracking down whether there's an expiration policy to inform 4th item. my next step: gather data to compare against LHDI's assertion. ([ref](https://dsva.slack.com/archives/C04QLHM9LR0/p1720634596769249?thread_ts=1720558138.879729&cid=C04QLHM9LR0))

@nelsestu : let me know if you recommend against my next steps, and if you recommend moving this 4th item to a new ticket?

**Comment by nelsestu** [comment]
@BerniXiongA6, I created the following ticket: https://github.com/department-of-veterans-affairs/abd-vro/issues/3183
As Lisa indicates in her comment, our previous understanding of SecRel signature expiration was incorrect.  The new ticket is now a documentation and team communication task, so the fourth bullet is not needed and additional clarity is coming.

**Comment by BerniXiongA6** [comment]
Thanks @nelsestu 

Hey @lisac would you mind editing this current ticket to reference that the 4th bullet will be completed by Erik's new ticket #3183? Then when you're ready to close it, I think it's safe to do so. Thanks all!

cc: @meganhicks
