### ISSUE TITLE
Sprint B

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3172]
# Sprint 
---
<img src='https://upload.wikimedia.org/wikipedia/commons/1/14/Pikes_peak_highway_big_foot.jpg' height=250/><img src='https://upload.wikimedia.org/wikipedia/commons/9/99/Affiche_Bigfoot.jpg' height=250/>
<details>
<summary>Facts about Bigfoot</summary>

*alias: Sasquatch*

Lives in the Pacific Northwest. Discovered in 1958. Described as ape-like, covered in shaggy dark hair. Throws rocks as territorial displays and for communication. Featured in American and Canadian folklore. Cousin to the Yeti (Himalayas) and Yowie (Australian Outback). 6-10 ft tall (estimated), footprints measuring 16 inches long. 

Distinctive feature includes glowing eyes (note: other animals with this adaptation include owls, raccoons, opossums, and some spiders; however, primates lack this adaptation).

Recent sightings: Colorado in Oct 2023 ([ABC News](https://www.youtube.com/watch?v=isB0-GSvFzA)) ; Norfolk in Jan 2024 ([DVIDS](https://www.dvidshub.net/news/462400/bigfoot-sighted-onboard-naval-station-norfolk))

----
</details>

# Capacity
The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 85.6%
All UX: 27.9%
All Team: 78.3%
(Total points VRO team can handle this sprint: 18.8)

## Carryover from Previous Sprint

- [x] Enhancement to help EP Merge metrics Enhancement to help EP Merge metrics #3213
- [x]  DLQ ticket #3238. 
     - [x] add-on:  #3311
- [ ]  Custom Monitoring for Rabbit MQ and K8s termination grace period department-of-veterans-affairs/abd-vro#2817
- [x]  Configure ArgoCD for Contention Classification (CC) department-of-veterans-affairs/abd-vro#3092
- [ ]  ArgoCD final steps for partners ArgoCD final steps for partners #3176

# Sprint Plan

## Sprint Goal:
Within the first week of the sprint, complete the comparison between Streamlit and PGAdmin #3235 for discovery work. Present the findings to the entire team so we can determine which tool to use for our Data Visibility Proof of Concept.

### Data Visibility

- [x] Discovery on Steamlit vs/ PGAdmin #3235

### Metrics 

- [x] Investigate ways to automate MTTR #3325

### Improve the Partner Team Experience
Bianca is out 1/2 the Sprint
- [ ] Complete Deployment Requests - Prototype, Launch, and Comms #3292 **_(Per Bianca, moving this ticket out of Sprint B and back into Product Backlog. Should bring it into a future sprint.)_**

### Partner Team Requests
- [x] Enhancement to help EP Merge metrics Enhancement to help EP Merge metrics #3213
- [x]  DLQ ticket department-of-veterans-affairs/abd-vro#3238

### Monitoring and Alerting
- [ ] Explore a custom RDS monitoring solution so we can create a retention and storage policy #2116
- [ ]  Custom Monitoring for Rabbit MQ and K8s termination grace period department-of-veterans-affairs/abd-vro#2817
- [x]  Understating RabbitMQ downstream vulnerabilities #3306

### Improve Deployment
- [x]  Configure ArgoCD for Contention Classification (CC) department-of-veterans-affairs/abd-vro #3092
- [x]  ArgoCD final steps for partners ArgoCD final steps for partners #3176
- [ ]  Develop a migration strategy for ArgoCD #3042
- [ ]  Configure ArgoCD svc-bip-api for Prod cluster #3041

### On call
- [x] On call Primary and Secondary #3302  Kyle and Ponnia 

### Demo Plan
What could we demo?
- ArgoCD should be fully functional 
- New Deployment Process 
- Streamlit vs/ PGAdmin comparison 

# Unplanned Work (these tickets were added post-Sprint Planning)
- #3311
