### ISSUE TITLE
Sprint C

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3173]
Sprint C

### Cerberus 
---
<details>
<summary>Cerberus is a multi-headed dog who guarded Hades</summary>
<img width="305" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1LQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a600819d9be55f20355600915ad00dba8ab53fb0/cerberus.png" alt="cerberus.png" />

[Cerberus](https://www.greekmythology.com/Myths/Creatures/Cerberus/cerberus.html) is a multi-headed dog from Greek mythology, who guarded the gates of the Underworld, preventing the dead from leaving, and making sure that those who entered never left. [source](https://www.greekmythology.com/Myths/Creatures/Cerberus/cerberus.html). To many Cerberus is the three-headed dog that guarded hades, but the subject of exactly how many heads highly contradictory throughout history:
* First written mention comes from 8th or 7th century BC poem, written by Hesiod, who described him as having 50 heads! As was the custom, the poem was passed down orally for generations, and descriptions of Cerberus have changed over time. 
* Oral histories have a tendency towards exaggeration, so around 522–443 BC, the poet Pindar described Cerberus as having 100 heads. 
* Having so many heads started decreasing in popularity.  Maybe it was something about writing it instead of singing it, or maybe it started to occur to people how small each head would have been, thus distracting from the terror it was meant to instill.  What ever the reason, by around 50 BC most everyone would have agreed that Cerberus had three heads. 
* Some descriptions grant Cerberus snake-like features, or actual snakes as body parts. 
* The Latin poet Horace depicted Cerberus as having one dog head and 100 snake heads.
* Dante described Cerberus as a "great worm" with human hands and talons. 

No matter the exact circumstances of Cerberus's description, he almost always had a hound or hound-like head. He guards the gates of the underworld, preventing the dead from leaving and the living from entering. This is an important job and Cerberus was generally very good at his work. Successfully evading Cerberus was an extremely rare feat, typically reserved for heroes of exceptional ability or those with divine assistance. For most mortals, Cerberus remained an insurmountable guardian, effectively preventing unauthorized entry to or exit from the Underworld. Regardless of which plane of existence you inhabited, Cerberus was there to meet escapees with multiple heads, ready to distribute a gruesome devouring, from which, the inability to share your story turns out to be a common side effect.  When devouring a live human, Cerberus's job description switches to ensuring that the victims of his work will never escape Hades. Oddly, Cerberus is not typically described as devouring the souls of the dead in Greek mythology, which raises several existential questions about the nature of souls:
- Are souls just easily scared off, or dissuaded from any attempt to exit?
- Is the fate of a Cerberus consumed souls, oblivion? such that they might simply cease to exist, ending their afterlife journey.
- Would they be simply returned to the Underworld, required to pay another toll to cross the river Styx in order to continue their afterlife sentencing?
- Being devoured by Cerberus could theoretically be part of a rebirthing process, which offers a satisfying symmetry to the situation with live humans continuing in an afterlife existence. 
- Or might souls be sent to Tartarus, which is the deepest and most terrible part of the Underworld, as a form of punishment?

This brings us to the ones that got away, the humans who cheated death, successfully navigate the underworld and lived to tell about it. Yes these are the stories that make it into oral traditions, get carved into stone tablet, and survive the test of time.
Fans of the Harry Potter series will recognize the story of Orpheus, a legendary musician who used his lyre to play such beautiful music that Cerberus fell asleep, allowing him to pass safely.  In the story of Cupid and Psyche, Cupid advises Psyche on a drugged cake to make Cerberus drowsy and easier to pass by. It is not all sleep induction and stealth maneuvering though. Diversion, magic, divine intervention and strength, yes with the proper motivation and exceptional talents you too might cheat death.

It wasn't just the number of heads that  had, but it was also how many other monsters were among the siblings of Cerberus. Depending on the author, Cerberus's siblings included, the [Sphinx](https://www.greekmythology.com/Myths/Monsters/Sphinx/sphinx.html), the [Nemean Lion](https://www.greekmythology.com/Myths/Monsters/Nemean_Lion/nemean_lion.html), the [Caucasian Eagle](https://www.theoi.com/Ther/AetosKaukasios.html), the [Crommyonian Sow](https://www.greekmythology.com/Myths/Monsters/Crommyonian_Sow/crommyonian_sow.html), the [Colchian Dragon](https://www.theoi.com/Ther/DrakonKholkikos.html), [Ladon](https://mythopedia.com/topics/ladon), [Scylla](https://www.greekmythology.com/Myths/Monsters/Scylla/scylla.html) and [Keto](https://www.theoi.com/Pontios/Keto.html) the mother of the Gorgons

----
</details>

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

**UPDATED 8.28.24
All Eng: 74.7% (16.4 points)
All UX: 83.6% (2.5 points)
All Team: 75.8% (All VRO Team can handle a total of 18.9 points)**

_**Capacity notes from Berni:** Includes Labor Day closure, Ponnia OOO 8/30-9/9, and Derek being added to "Devoted to VRO team = 33%" and "Working on Sprint Commitments = 65%" << which is the same % for everyone else._

_**Note:** Not included in capacity planning numbers, Megan is OOO 8/30-9/20. Berni will backfill the PM role in addition to DM role during this time._
Mason out 9/9-9/12 <<< BX NOTE: Thank you, this has been added to the new capacity calculation / edited above.

# Sprint Plan 

1. Develop a plan to automate secret and certificate management to streamline our deployment process, enabling us to finalize and deliver the MVP "Improving Deployments". 
2. Begin implementing the tool we will use to enable the CC team to query contention data. 

## Carry Over (if any): Are there any tickets that will carry over from previous sprint?

- [x] Custom Monitoring for Rabbit MQ and K8s termination grace period #2817
- [x] ArgoCD final steps for partners #3176
- [x] Develop a migration strategy for ArgoCD #3042
- [x] Configure ArgoCD cut over for Prod cluster all services #3041
- [ ] Complete Deployment Requests - Prototype, Launch, and Comms #3292 (In Progress - continue to work in Sprint 1)
- [ ] Explore a custom RDS monitoring solution so we can create a retention and storage policy #2116 (Blocked by LHDI - continue to work in Sprint 1)

## Sprint Goal:

Now that ArgoCD is complete (almost!), let's wrap up by fixing the secrets across our environments.

### Data Visibility
- [x] After doing research #3235, determine what the POC should be and update the Epic to reflect it. Product Task
- ~~Run the Streamlit idea by our ISSO #3409~~ _Per team: move out of Sprint C, to be pulled into future sprint when ready to work on_

### Keep the platform running
- [x] Upgrade ArgoCD config.json to Use Required Syntax #3309
- [x] RabbitMQ: Investigate Queue/Exchange configurations #3329
- [x] VRO: Update Queue/Exchange configurations (BIP/BGS/EP Merge) #3330
- [x] Update Dependabot documentation #3234 - cheng finished this prior to the sprint starting 

### Partner Team Requests
- [x] Submit request for claim events #3336 - Product Task 

### Incidents
- Did we have to pull any in?

### Metrics
- [ ] Define how we will measure Impact to Veterans/VSRs/RVSRs based on tools built on VRO #3192 _**<<< BX: Wasn't worked on, let's move to Sprint 1 (9.10.2024 - 9.23.2024)**_

### Improve Deployments
- [x] Configure ArgoCD + Vault for svc-bip-api #3037
- [x] Configure ArgoCD + Vault for BIE #3315
- [x] Configure ArgoCD + Vault for BGS #3316
- [x] Configure ArgoCD + Vault for rabbitmq  #3319

### Who is On Call?

- [x] On call Primary and Secondary #3384

### Demo Plan
- What could we demo?

# Unplanned Work (these tickets were added post-Sprint Planning)
-

**Comment by BerniXiongA6** [comment]
End of sprint delivery metrics: VRO team completed Sprint C at 111% of team capacity plan and 100% of sprint plan. Bravo team!
