### ISSUE TITLE
Sprint 1 (9.10.2024 - 9.23.2024)

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3248]
**Sprint 1 (9.10.2024 - 9.23.2024)**

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

**All Eng:** 91.2% (15 pts)
**All UX:** 92.9% (2.8 pts)
**All Team:** 91.4% (17.8 pts)
**Adjusted after carry-over work:** 17.8 pts - 3.5 pts = 14.3 pts we can take on in Sprint 1
**Capacity notes from Berni:** There was no known planned time off, Lisa sick 9/10

## Carry-Over Work

**Are there any tickets that will carry over from previous sprint?**
- (1.5) Explore a custom RDS monitoring solution so we can create a retention and storage policy #2116 (Paul working with LHDI to get superuser access)
- (2) Complete Deployment Reminder Workflow - Prototype, Launch, and Comms #3292 (Bianca continue work in progress)

# Sprint Plan 

## Sprint Goal:

- Primary Goal: Wrap up secret migration to Vault (continuing ArgoCD implementation)
- ~Secondary Goal: Complete MVP outline and seek alignment before moving the project into the development phase~ <<< Per OCTO: Reprioritize to have team start working on discovery for Zero Silent Failures initiative (New Epic #3471)

### Data Visibility (Epic #2918)
Design
- [ ] [Design] (2) Develop a minimum viable product outline and seek alignment #3410
Product
- [ ] (0) #3418
All Team
- [ ] (1) #3440

### Improve the Partner Team Experience (Epic #2961)
Design
- [x] Complete Deployment Reminder Workflow - Prototype, Launch, and Comms #3292 (Bianca continue work in progress)
- ~Top Use Cases: New Feature Requests - Research and Ideation #3242~ <<< Can bump to Sprint 2 if unable to finish in Sprint 1 <<< Bumping to Sprint 2 due to new effort # taking top priority

### Keep the platform running (Epic #2806)
Engineering
- [ ] (3) BIE: Update svc-bie-kafka to persist contention event in the application #3334 (already in progress)

### Partner Team Requests (Epic #3147)

- [ ] None at this time

### Monitoring and Alerting (Epic #2335)

- [ ] (2) Explore a custom RDS monitoring solution so we can create a retention and storage policy #2116 (Paul working with LHDI to get superuser access)

### Incidents (Epic #3148)

- [x] (1) RabbitMQ / BIP api failures #3436

### Metrics (Epic #3190)
- None in Sprint 1
- ~Define how we will measure Impact to Veterans/VSRs/RVSRs based on tools built on VRO #3192~ <<< move out of Sprint 1 due decreased capacity, tentatively add to Sprint 2
- ~Define merged PR to PROD #3193~ <<< move out of Sprint 1 due decreased capacity, tentatively add to Sprint 2

### Improve Deployments (Epic #2615)
Engineering
- [x] (2) Configure ArgoCD + Vault for EPMerge #3318
- [ ] (2) Configure ArgoCD + Vault for CC  #3314
- [x] (2) Configure ArgoCD + Vault for MaxCFI #3317 ~NOTE: If we have capacity, VRO engr can pull this one back into Sprint 1~ Ponnia pulled in and is now working on
- [ ] Configure ArgoCD + Vault for db-init #3320 ~<<< low priority, can move out of Sprint 1~ Kyle pulled in and is now working on
- ~Configure ArgoCD + Vault for domain-xample #3323~ <<< removing from Sprint 1, no longer needed
- ~Configure ArgoCD + Vault for dev-tools #3321~ <<< low priority, can move out of Sprint 1
- ~Develop a migration strategy and cut over for Secret Automation Work #3356~ <<< move out of Sprint 1
- ~(?) Needs refinement #3424~ <<< VRO to refine in Sprint 1, and can tentatively pull in to Sprint 2)

### Who is On Call?

- Primary: @PaulKBaumann 
- Secondary: @lisac 
- [x] [Engineer] (2) On call Primary and Secondary for Sprint 1 #3439

### Demo Plan

- What could we demo?

# Unplanned Work (these tickets were added post-Sprint Planning):
_List any new tickets here (please notify Product/Delivery when there is crucial work to be added to the sprint after planning day)_
- [X] #3423
- [X] #3437
- [x] #3462
- [x] #3467 
- [x] #3472 - Anyone can pick up this ticket ahead of Sprint 2 now that we're prioritizing "Silent Failures" work, per OCTO's request.

**Comment by BerniXiongA6** [comment]
VRO Team completed 17 points out of 17 planned points (100%) and 95% of their capacity plan. Bravo everyone! cc: @amylai-va
