### ISSUE TITLE
Evidence of condition – file clean up

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/abd-vro#3297]
```[tasklist]
### Tasks
- [x] scrub notes / transcripts of PII/PHI
- [ ] Set recordings to be deleted (Shannon?)
- [x] Update [ABD Design and Research Index](https://docs.google.com/spreadsheets/d/1ooJLEU9U72kNBoc1hpc643MfsjlfujOs5LcFjDYOEi0/edit?gid=2037767115#gid=2037767115)
- [x] Update va.gov-wide equity tracker
```
Per this guidance: https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions

**Comment by katelyncai** [comment]
We are holding onto recordings for the time being. Closing this out.
