### ISSUE TITLE
Sprint 2 (9.24.2024 - 10.7.2024)

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3303]
**Sprint 2 (9.24.2024 - 10.7.2024)**

# Sprint Plan 

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 92.4% (15.3 pts)
All UX: 55.6% (1.7 pts)
All Team: 85.3% (16.9 pts)

Capacity notes from Berni: Derek 50%, Katelyn 33%, Derek 1/2 day 9/26, Katelyn 10/4, Bianca 9/30-10.4

## Carry-Over Work

**Are there any tickets that will carry over from previous sprint?**

- [x] #2116
- [x] #3467
- [x] #3334
- [x] #3320

# Sprint Plan 

## Sprint Goal:
Primary: Investigate and determine if VRO has silent failures - by October 1
Secondary: Update Datadog user for postgres due Oct 10 #3493
Tertiary: Complete Secret Management, then shift focus to enabling RDS to be queried.

### Silent Failures (Epic #3471)
- [x] #3473 **(Sprint goal)**
- [x] #3476 **(Sprint goal)**
- [x] #3477 **(Sprint goal)**

### Data Visibility (Epic #2918)

- [x] Workshop Streamlit MVP with team #3440

### Improve the Partner Team Experience (Epic #2961)
- [ ]  Partner Team Production Deployment workflow - Refine and Official Launch #3500

### Keep the platform running (Epic #2806)

- [ ] Consolidate all on-call data and instructions in one location #3519
- [x] Update Datadog user for postgres due Oct 10 #3493 **(Sprint goal)**

### Monitoring and Alerting (Epic #2335)

- [ ]  track rabbitmq metrics in datadog #3482   

### Incidents (Epic #3148)

- [x] Fix db-init Flyway migration issues #3521

### Improve Deployments (Epic #2615)

- [x]  #3321 **(Sprint goal)**

### Who is On Call?
- [x] #3499
- Primary: @PaulKBaumann 
- Secondary: @Ponnia-M 

### Demo Plan

- What could we demo?

# Unplanned Work (these tickets were added post-Sprint Planning):
- [x] Application Alerting for BIP #3017
 - [x] svc-bip-api: Detect dropped RabbitMQ connection #3509
- [ ] Onboard Gabriel Zurita to VRO #3549

**Comment by BerniXiongA6** [comment]
Great job VRO Team! The sprint closed at 136% of team capacity (23 pts / 16.9 pts) and 144% of sprint plan (23 pts / 16 pts). cc: @amylai-va @meganhicks
