### ISSUE TITLE
VRO: Update Queue/Exchange configurations (BIP/BGS/EP Merge)

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3330]
# Summary
Implement changes resulting from the investigation in ticket #3329.

# Acceptance Criteria
All services that declare queues / exchanges are updated with the configuration changes.  Updates include declarations as well as any affected unit/integration/end2end tests. 

### Tasks
- [x] Update svc-bgs-api queues/exchanges 
  - #3402
- [x] Update svc-bip-api queues/exchanges 
  - #3405
- [x] Update EP merge queues/exchanges
  - #3402
  - #3405
- [x] Update RabbitMQ config to add per-service policies (bip/bgs only)  
  - #3407 
  - for BGS this Covers #3328 
- [x] Determine deployment process - see comment below
- [x] Document new RabbitMQ Exchange/Queue Rules in Wiki
  - See [section in wiki](https://github.com/department-of-veterans-affairs/abd-vro/wiki/VRO-RabbitMQ-Strategy#vro-rabbitmq-rules) 
- [x] Facilitate Engineer discussion on the proper direction of bie-kafka and saving events to the db
- [x] Create Follow on for BIE Kafka Services 
   - #3334

**Comment by dfitchett** [comment]
Deployment:
1. Redeploy RabbitMQ so that policies are created on startup
2. Redeploy EP Merge - note that it will start, but it will fail to connect to the passively declared queues / exchanges but it will continue attempts to reconnect
3. Redeploy BIP
4. Redeploy BGS
5. Manually via RabbitMQ clean up any old queues/exchanges
