### ISSUE TITLE
BIE: Update svc-bie-kafka to persist contention event in the application 

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3334]
This ticket was repurposed after discussions of the results of #3329.

# Summary
~~Currently, when BIE event message are sent from the BIE Kafka stream to RabbitMQ, if the xample-workflow application is not available, those messages will sit on the queue. In the event that they are dead lettered for some reason, when the xample-workflow application is next available, it should attempt to process those messages so that the data is not lost.~~

Currently the saving of contention events is split between `svc-bie-kafka` and `xample-workflow`. This adds complexity for a simple task and also risks further loss of data in the event that `xample-workflow` is down and the events are not consumed from rabbitmq and later saved to the RDS instance.

This task is to make `svc-bie-kafka` persist the events from BIE Kafka stream, and then put those events on the appropriate exchange. In addition, with the events being saved in `svc-bie-kafka` there is no longer any need for `xample-workflow`. 

# Acceptance Criteria
~~BIE Event messages that are dead lettered are reprocessed and the data is saved to the database.~~
- [x] `scv-bie-kafka` is updated to save the contention events to the database
  - #3441 
- [x] `scv-bie-kafka` queue/exchange configurations are updated to optimize publishing / consuming of events off of RabbitMQ
   - things to consider:
     - possible reconfiguration/reconsolidation of exchange/queues based on results of #3329
- [x] `svc-bie-kafka` argocd applications vault config is updated:
   - https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/pull/86
- [x] `xample-workflow` is updated to remove the persistence #3441 
- [x] Identify next steps with the remainder of xample workflow
  - [x]  Remove xample-workflow #3442
  - [x] create ticket to remove xample-workflow from argocd vault #3501
  - [x]  Close out tickets that are no longer necessary
     - #3019 
     - #3323 
- [x]  Unit/Integration/End2End tests are created/updated as necessary.~~

**Comment by dfitchett** [comment]
For whomever gets this ticket, this is a great opportunity to create an end to end test using Github Actions!

**Comment by dfitchett** [comment]
Currently blocked by successful deployment of svc-bie-kafka to dev. LHDI ticket [here](https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/71).
