### ISSUE TITLE
Sprint 3 (10.8.2024 - 10.21.2024)

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3335]
**Sprint 3 (10.8.2024 - 10.21.2024)**

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 58.4% (11.7 pts)
All UX: 90.9% (3.6 pts)
All Team: 63.8% (15.4 pts)

Capacity notes from Berni:
Gabe and Cheng are represented as 1 role in the capacity calc; Derek is on VRO 70% of the time; there are 2 open roles (backfills for Lisa and Mason are not yet confirmed); Derek PTO 3 hours 10/10; Kyle PTO 10/11; Office closed 10/14; Cheng travel on 10/8-9

## Carry-Over Work

**Are there any tickets that will carry over from previous sprint?**

- [ ] #2116 Explore a custom RDS monitoring solution so we can create a retention and storage policy 
- [x] #3476 Log of est. vol. silent failures (1 pt)
- [ ] #3500 Partner team production deplmt workflow (1.5 pt)
- [ ] #3482 alerting rabbitmq metrics in DD (2 pts)
- [x] #3549 Onboard Gabe (0 pts)

# Sprint Plan 

## Sprint Goal:
Complete the incident response workflow for Silent Failures, ensuring updates are deployed within one sprint, and finish the rollover silent failure work so we can finalize the initiative and transition to data visibility efforts. 

### Silent Failures (Epic #3471)

- [x] Application Alerting for BIP #3017
- [x] Add monitor tags to svc-bip-api #3528
- [x] Fix bug in BGS returning wrong values on downstream BGS exception #3526
- [x]  Application Alerting for BGS #3018
- [x] svc-bip-api: Detect dropped RabbitMQ connection #3509
- [x] svc-bgs-api: Detect dropped RabbitMQ connection #3530
- [ ] Update the Incident Response Workflow #3478
- [x]  #3476 Log of est. vol. silent failures
- [ ]  #3482 alerting rabbitmq metrics in DD

### Data Visibility (Epic #2918)

- [ ] Develop a Product Brief for Data Visibility 
- [x] Set up Generic Python Project #3552
- [ ] Set up a Python Project for Streamlit and deploy to prod #3575
- [ ] Structure Single Page App for Streamlit #3554
- [ ] Understand CC query use cases #3553

### Improve the Partner Team Experience (Epic #2961)

- [ ] no work

### Keep the platform running (Epic #2806)

- [x] Upgrade to Secrel to Version 6 #3577
- [ ] work with LHDI on migration of auth tools 10/21 for one call #3535
- [ ] BEP aka BGS Testing Support 10/21 #3569
- [ ] Tickets for Gabriel -Dependency Management Page on wiki #3036 and Update Datadog documentation to represent Partners on the wiki #3563

### Partner Team Requests (Epic #3147)

- [ ]  no work

### Monitoring and Alerting (Epic #2335)

- [ ]  Working towards the same goals in the Silent Failure Epic 
- [ ]  Follow ups on #2116? 

### Incidents (Epic #3148)

- [x] Incident Reported: RabbitMQ non-prod pods not starting #3574

### Improve Deployments (Epic #2615)

- [x] Shared ArgoCD Secrets Implementation #3520

- [ ] Secrets Automation Cleanup #3540 (stretch goal)

### Who is On Call?
- [ ] On call Primary and Secondary #3576

- Primary: Ponnia 
- Secondary: Kyle 

### Demo Plan

- What could we demo?

# Unplanned Work (these tickets were added post-Sprint Planning):

**Comment by BerniXiongA6** [comment]
cc: @amylai-va
