### ISSUE TITLE
Claim Tracker: Implement REST endpoint to accept request to track claim

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3362]
# Summary
Create a new service in VRO that accepts a request to track a claim with respect to a feature flag.

# Implementation Details
Details can be found in the design presentation [Feature Effects on Claim Lifecycles](https://docs.google.com/presentation/d/1xA5-254JhOh_4bsc4CADnQKkstllpkt8gpNyt3u9WDo/edit?pli=1#slide=id.g2f38420da69_0_301).

# Acceptance Criteria
- [x] New service is stood up in VRO
- [ ] The database table and orm to save the claim ID + meta is created
- [x] The service creates a REST endpoint that accepts request and saves model to table
- [ ] Unit tests
