### ISSUE TITLE
VA.gov: Create EOC education behind Feature Toggle

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3363]
### Description
This ticket tracks the implementation of the actual education and the feature toggle to control it

### Blocked By
See task list below...

### Acceptance Criteria
- Create the EOC MVP education
- Create the logic that triggers showing it (specific contentions?)
- Place it behind a feature flag
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3368
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3369
- [ ] https://github.com/department-of-veterans-affairs/abd-vro/issues/3370
```
