### ISSUE TITLE
Sketch ideas for EOC for posterity

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3369]
## Context

We're wrapping up the EOC project. In order to ensure what whatever team can pick it up where we left off, we're sketching out some ideas while they're still fresh. 

```[tasklist]
### Tasks
- [x] Sketch out a bunch of ideas
- [ ] Select 2-3 to refine with OCTO stakeholders
- [ ] Refine those 2-3
- [ ] Document for posterity
```

**Comment by carodew** [comment]
Update – based on feedback from Jen, we decided we didn't need to refine a few ideas, we're good with the rough sketches. Marking this as done.
