### ISSUE TITLE
Meta-analysis of existing research on supplemental claims

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/abd-vro#34]
## Background

Other people, particularly the Lighthouse team, has done a fair amount of previous research on supplemental claims. This ticket covers reviewing that research and pulling some (very scrappy) insights or threads for further inquiry. 

## Documents 

- [x] [LH supplemental claim product brief](https://dsva.slack.com/files/UJ1LFHFCN/F03ETTA5YTY/lh_supplemental_claim_brief.pdf) 
- [x] [20211123 Supplemental claim discovery -- VSOs: Research report](https://dsva.slack.com/files/UJ1LFHFCN/F03EL23TSS3/supplemental_claims_vso_research.pdf)
  - VSOs will use a supplemental claim to reopen the timer on filing an appeal. VSOs perceive the Board to be more likely to give a favorable ruling. 
  - Some mentions of a veteran not remembering filing a claim in the past, not having the previous denial, or not knowing which form to use. 
  - Older veterans don't always trust digital submissions. Sometimes will want to submit the same claim both digitally and via paper, just in case. 
  - Some VSOs like to submit PMRs themselves so they can ensure that the right evidence is in the file, rather than have the VA request those directly. This may have implications for what we can OCR from the eFolder.
  - VSOs sometimes use the Stakeholder Enterprise Portal (SEP) to submit a supplemental claim but that portal doesn't specifically handle 0995s. These end up getting labeled as 'correspondence.'
  - VSRs receive claims that are submitted on the wrong form, so those claims have to be canceled and the veteran has to file again on the right form. Sometimes that prompts the veteran to seek the help of the VSO.
- [x] [20210928 Supplemental Claim Discovery - VA 
Administrators: Research Report](https://dsva.slack.com/files/UJ1LFHFCN/F03EL24675M/supplemental_va_admin_research.pdf)
  - One of the biggest errors that claims assistants see is with missing or invalid signatures. When this happens they send a notice to the veteran and add a 30 day hold on the claim. 
  - The 5103 checkbox on the form can waive the requirement that the VA send the POA notice to the veteran. Skipping this step can save 30 days processing time, but not all veterans or VSOs are aware of this. This is different from the 526ez.
  - Missing 4142/4142A forms can delay processing. 
  - Recent changes meant that ITFs count for supplemental claims, but not all adjudicators are aware of it (or were at the time of this study). (Note: This was also true of VSOs)
  - supplemental claims are often submitted without additional evidence. This creates a lot of low- or no-value-add work on the part of the VA. (Note: could these be claims that are intended to reopen the appeals window?) 
  - this is particularly true if the claim has already been denied many multiples of times in the past. This means it takes the R-VSR a lot of time to review the evidence and build the evidence list just to deny the claim.
  - the issue of a veteran submitting multiple single issue claims happens with supplemental claims as well, which creates more back end headaches. This is compounded with many of those issues have been denied multiple times already.
  - documents come in with incorrect file names, which then adjudicators have to correct. a supplemental claim form could be hiding out as a different type of document. 
  - VSRs and RVSRs will edit the contention names in Caseflow. 
- [x] [20220131 Supplemental Claim Discovery - Veterans: 
Research Report](https://dsva.slack.com/files/UJ1LFHFCN/F03FQCC1JSU/supplemental_veteran_research.pdf)
  - Veterans don't understand what it means to say that they have or have not received the duty to notify form, which is a yes/no question on the supplemental form (not on the 526 form). Checking 'no' means more time processing the claim. 
  - Non veteran claimants have their own set of challenges, not fully explored in this research. 
  - Veterans don't understand what counts as 'new and material' evidence to support their supplemental claim. 
- [x] [Supplemental claims high level workflow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1647639982807/fa3be40a5b7bbd09adcc4d2a9a5e575525aee68f?sender=u7a056d800c6b0238f8a14300)
- [x] [Lighthouse Mural of AMA processes ](https://app.mural.co/t/lighthouseapiplatform7991/m/lighthouseapiplatform7991/1631736307705/31e23e9b9754a0ffceecdc2f037dc86976553b08?sender=premalshah3040)
- [x] [Mural of supplemental claims high level workflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1647639982807/fa3be40a5b7bbd09adcc4d2a9a5e575525aee68f?sender=carolyn1198)
- [x] [Supplemental Claims 101](https://www.notion.so/Supplemental-Claims-101-19ffc9bee2fd416dab9e7311ab908d2d)

### Lighthouse specific research
 
Below links are from [VSO Research aggregation](https://docs.google.com/document/d/1I4nJlqiG1uaBhfZ8mdir5NVmDaAYpYLignFwp93hDnI/edit)
   - [x] [2019 10 VSO Appeals (HLR) Discovery ](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2019-10-VSOs-Appeals-Higher-Level-Review-Discovery-Research-with-VSOs)
  - [x] [VSOs COVID effects](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2020-04-VSOs-Covid19-and-1010EZ-Form-Discovery-Research-with-VSOs)
  - [x] [VSO Appeals (NODs) Discovery ](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2020-12-Notice-of-Disagreement-VSOs-Discovery-Research)
  - Previous mistakes in decisions are hard to correct. VSO reps try not to include specific dates or issues in appeals because they see those as potentially leading to a negative outcome for the veteran. 
  - VSOs don't like it when veterans use ebenefits to manage their claim because 'they mess it up'
  - Many people at a VSO will work on an appeal – it's a team effort. Authentication and permissions to various software does not support this.
  - Appeals statuses (and claims statuses) aren't particularly descriptive or useful. VSOs will call the Board to find someone who can give an update (cost for the VA and the VSO)
  - another example of a veteran forgetting that they had an appeal in process and so they submitted a new appeal on the same thing
-  [x] [VSOs POA Experience](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2021-04-Power-of-Attorney-Experience-with-VSOs)
  - Representatives do not get notified when access to VBMS has been turned on or when they lose power of attorney, which happens often.
  - Representatives main goal is to get their claims in front of the right adjudicator quickly, and they will use the systems available to accomplish this goal

### VA.gov research

- [ ] [Find/appoint Rep functionality ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/vso-discovery-interviews/vso-discovery-research-findings.md)*BROKEN LINK*
- [ ] [526 Self Service Claims for Increase](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/jul-2018) *BROKEN LINK*
- [x] [VSO Journey Map - Disability Comp Claim](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/discovery/2017-vso/output/journey-map/vso-journey-disability-claim-11x17-10.20.17.pdf) 
### Other

- [x] [CSRA Profile readout](https://dsva.slack.com/files/UD44PE3B2/F03JDTHUWTG/csra_profile_readout_d2_d3_091516_lores_part2.pdf) **Note: well worth reading!** 

Distills findings into the following seven principles. Has sacrificial concept sketches that are good idea fodder.

**1. GIVE ME ACCESS**
Facilitate my effective use of VA services by giving me tools that are accessible and useable, regardless of my age or ability.
**5. CONNECT ME**
Introduce me to people that can grow my knowledge of VA services and link me to services I am entitled to.
**2. ENABLE ME**
Provide me with personal and actionable information to reduce the burden I feel and allow me to positively engage with VA.
**6. HELP ME**
Direct me to specific answers to my questions, accurate information, and helpful people to talk to.
**3. SECURE ME**
Show me that you're keeping my personal information secure.
**7. SUPPORT ME**
Guide me through my VA experiences in a way that is as relevant as possible to me and my family.
**4. RESPECT ME**
Show that you know and value me by giving me relevant advice based on my personal experiences and information.

## Out of scope
