### ISSUE TITLE
Sprint 6 Plan

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3601]
**Sprint 6: November 19 - December 2, 2024**

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 45.4% (9.1 pts)
All UX: 67.4% (2.7 pts)
All Team: 49.4% (11.8 pts)

Capacity notes from Berni: includes Thanksgiving holiday, known time off, company holiday schedule, medical leave, wellness time: Megan OOO 11/21 - 12/4; Katelyn 11/22-29; Derek 11/27-29; Kyle 11/27-29; Gabe 11/27-29; Nava closed 11/28-29; A6 closed 11/28 

# Sprint Plan 

### Decommission VRO (Mural board: [link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730393969495/a456b366e448f7025007ce4db200b7464a130f33))
- [x] Develop plan for shutting down EP Merge (#3723)
- [ ]  ~~Begin executing EP Merge shut down tasks~~ -- deprioritized this priority and moved "executing shutting down EP Merge" tasks out to allow EE Team to confirm when we can turn off EP Merge
- [x] VRO Team members continue onboarding to VA Platform (epic #3691 )

### Keep the platform running (Epic #2806)
- [x] On call for Sprint 6 #3736

#### Who is On Call?
- Primary: @gabezurita 
- Secondary: @brostk 

# Unplanned Work (these tickets were added post-Sprint Planning):
- [x] TOP PRIORITY: Develop plan for shutting down BIE-Kafka and begin executing those tasks -- pulled this priority into current sprint since BIE-Kafka is ready to be shut off (and we're still awaiting confirmation from EE team on when we can execute on shutting off EP Merge)

**Comment by dfitchett** [comment]
Still holding on shutting down EP Merge. Shifting priority to shutting down BIE Kafka.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 is working on drafting the comms ([link](https://dsva.slack.com/archives/C07CKR6AX9S/p1732917488636999)) that VRO Team will send out when decommissioning services (will spin up a ticket before the end of the current sprint to manage this work. Thanks in advance to @bianca-rivera for offering to be an extra set of eyes when we're ready to refine the comms.
