### ISSUE TITLE
Sprint 7 Plan

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3621]
**Sprint 7: December 3, 2024 - December 16, 2024**

# Capacity

The percentages below reflect the amount of capacity the team members have to work towards sprint goals and priorities. Therefore, the sprint plan commitments should be reduced using these percentages. Note: includes time off, non-sprint commitments, and new team member ramp-up.

All Eng: 76.2% (15.3 pts)
All UX: 97.5% (3.9 pts) <-- @BerniXiongA6 @Joe-cox17 needs to be updated per capacity note below
All Team: 79.6% (19.2 pts)

Capacity notes from Berni: Megan OOO 12/3 - 12/4; Gabe 12/6, 12/13; Kyle 12/4; Paul 12/6; Ponnia 12/16; Bianca reduced capacity  to 20% due to supporting CC team AT usability testing study

Katelyn 12/4-12/9 (25% VRO, 75% EE); Derek 12/6 (70% VRO, 30% EE) **<<< Can change these percentages devoted to each team as needed** 

# Sprint Plan 

## Sprint Goal:
- [ ] Primary Goal: Finish shutdown of the BIE Kafka service #3756 

### Decommission VRO (Mural board: [link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730393969495/a456b366e448f7025007ce4db200b7464a130f33))
- [ ] VRO Team members continue onboarding to VA Platform (epic #3691 )
- [x] #3752 

### Keep the platform running (Epic #2806)
- [ ] On call for Sprint 7 #3819

#### Who is On Call?
- Primary: @Ponnia-M (for 12/16 only: @brostk )
- Secondary: @geoffrey-nava 

# Unplanned Work (these tickets were added post-Sprint Planning):
