### ISSUE TITLE
Onboard to VA.gov Platform

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3691]
This task is to ensure that ALL VRO team members who need to onboard to and get oriented on VA.gov Platform receives their VA Platform new team member checklist so that they can 1) get up to speed on the role of Platform, 2) acquire these Platform basics as quickly and efficiently as possible to make it easier to do their job, and 3) gain resources before they build MAXCFI and CC Applications in vet-api. 

AC: 
- [x] VA Platform resource has been contacted to identify which VRO team members still require orientation / onboarding to VA.gov Platform
- [x] VA Platform new VFS team member requests have been submitted for each VRO team member
- [x] Megan has completed VA Platform onboarding/orientation tasks
- [x] Bianca has completed VA Platform onboarding/orientation tasks
- [x] Derek has completed VA Platform onboarding/orientation tasks
- [x] Kyle has completed VA Platform onboarding/orientation tasks
- [x] Gabriel has completed VA Platform onboarding/orientation tasks
- [x] Ponnia has completed VA Platform onboarding/orientation tasks
- [x] Geoffrey has completed VA Platform onboarding/orientation tasks
- [x] Julius has completed VA Platform onboarding/orientation tasks
- [x] Paul has completed VA Platform onboarding/orientation tasks

**Comment by BerniXiongA6** [comment]
@meganhicks 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96730

**Comment by BerniXiongA6** [comment]
@dfitchett 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96738

**Comment by BerniXiongA6** [comment]
@brostk 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96739

**Comment by BerniXiongA6** [comment]
@Ponnia-M 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96742

**Comment by BerniXiongA6** [comment]
@bianca-rivera 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96744

**Comment by BerniXiongA6** [comment]
@PaulKBaumann 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96746

**Comment by BerniXiongA6** [comment]
@katelyncai 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96748

**Comment by BerniXiongA6** [comment]
@gabezurita 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96750

**Comment by BerniXiongA6** [comment]
@geoffrey-nava 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96756

**Comment by dfitchett** [comment]
> [@dfitchett](https://github.com/dfitchett) 's VA Platform new team member request has been submitted: [department-of-veterans-affairs/va.gov-team#96738](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96738)

@BerniXiongA6 I've actually already done the platform onboarding! See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62459). I will take this opportunity to review some stuff tho!

**Comment by gabezurita** [comment]
@BerniXiongA6, I should also be onboarded! See:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/68194

I'll double-check the new issue to see if anything has changed.

**Comment by BerniXiongA6** [comment]
@jahenkor-navapbc 's VA Platform new team member request has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97494

**Comment by BerniXiongA6** [comment]
Changing this ticket to an epic so that we can track individual team members' VA Platform tickets till closed.

**Comment by meganhicks** [comment]
@BerniXiongA6 I am done. How can I close this? I am not seeing an option.
