### ISSUE TITLE
Synthesis - overflow usability testing

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3882]
## Issue Description
- Follow guidance from VA Platform Research & Design on [conducting sessions](https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions)
- Discuss whether team wants to use recordings for future presentations

---
## Tasks
- [x] Add this issue to the relevant sprints and/or milestones
- [x] Create a synthesis Mural
- [x] Review interview notes and recordings and add observations into the Mural as stickies
- [x] Group similar stickies into themes, give each group a title
- [x] Priortize key findings
- [x] Develop recommendations
- [x] Review synthesis with Enablement Team

## Outputs
- [Synthesis Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1734634772316/c2265d4ecbd3828723aa1903d2e91919c20dd876)

**Comment by carodew** [comment]
Sorry I saw the term "usability testing in the issue title and got a little trigger happy on calling it done
