### ISSUE TITLE
Understand rationale for LH PDF generator

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3883]
## Issue Description
- From [sprint planning](https://docs.google.com/document/d/1yuMNUxspvYwGgXKmmx-VdWlZIG-rfD_8HwaamwIi11A/edit?tab=t.0#heading=h.2e3e434ifu05) on 12/18/24:
   - Jen – understand “the why” it goes through LH vs. vets-api. If we’d prefer to solve it with vets-api – that would helpful. Do we have to keep in in LH?
   - Even if we don’t pilot on the 526 first, that’s still obviously pretty important.
   - Possible Steve Albers, or Sam Wiley might have answers – could send them a slack message first.
   - How much does LH being and open API matter here? Was that part of the initial rationale to build a second PDF generator?
- See the comment below from the team's meeting with Sam Wiley (week of 1/20/25)
- Mack to continue pushing this forward in Sprint 11. 
- Jen's idea: contact Michael Harlow (he might know something about team firefly -- the LH PDF team -- prior to them owning it, it was owned by EVSS -- which is why it probably was separate from vets-api in the first place)
   - Michael works/ed on EVSS, and has intimate knowledge here about both EVSS and LH.
   - EVSS was not just one API, it was a family of 9 or so. They just replaced everything and moved to LH, so that's probably why it ended up this way.

---
## Tasks
- [x] Mack to reach out to Michael Harlow via Slack
- [ ] (as needed) Mack to set up addition meetings LH, and other stakeholders who are familiar with the LH PDF generator -- e.g. Emily, Aurora
- [x] Document our findings in this issue, ~and in our product brief~

## Acceptance Criteria
- [x] We understand the rationale for LH having built their own PDF generator (aside from what was already in vets-api)
- [x] We've documented our findings here, ~and in our product brief~
- [x] We have a better idea of how to reconcile this with our need to make changes to the 526 PDF LH generator... and we have enough background info to start thinking of alternate approaches and/or stop-gap solutions to this problem.

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`engineer`, `data science`, `design`, `research` , `product`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mackhowell-nava** [comment]
The team met with with Sam Wiley on 1/13/25 (unfortunately no root cause or info was discovered) -- [notes here](https://docs.google.com/document/d/1WjNnsY9MjFKnowftWPhKoLhTnje7Ek73XZrz1EAmAhA/edit?tab=t.0)

**Comment by mackhowell-nava** [comment]
### After Slacking with Michael Harlow + Yang (separately) here is the summary:

- A LH PDF endpoint was created to support the VA.gov 526 backup process, which sends PDFs to Central Mail on errors submitted through the LH 526 API.
   - It also replaces replace the “containerized” EVSS API
- Historical context:
   - When a 526 is established in VBMS, the signed and date-stamped PDF must be sent to the eFolder.
   - Before the LH 526 API existed, VA.gov used to use the EVSS API to ensure PDF delivery to the eFolder.
   - Before the EVSS API existed, eBenefits/SEP users generated the PDF as part of the submission process.
      - “Truly ancient stuff” -Yang
      - Jen: other teams are trying to get to the point of getting rid of that (accredited reps)
   - Reason: the 526 has always been responsible for creating it’s own PDFs (even back when it was by hand). Perhaps EVSS just couldn’t support other non-526 forms? (or wasn’t willing to on a reasonable timeframe)
- Next steps:
   - Michael: “I think Lighthouse can accommodate the new overflow style. Please work with the Lighthouse PDF generator backend manager robert.perea-martinez@adhocteam.us”
   - EE Eng brainstorm/recommendation → the LH Benefits Claims API could also use/cut over to the vets-api PDF generator. However, does that overlap with the LH team’s scope?


### RAW coversation below:
Hi Mack, I've been working with 526 submissions long before [VA.gov](http://va.gov/), so you came to the right place.
- Given your experience, do you recall the original rationale for keeping these PDF generation capabilities separate?

> The PDF endpoint is separate to support the [VA.gov](http://va.gov/) 526 backup process, which sends PDFs to Central Mail on errors submitting through the Lighthouse 526 API. Also, the EVSS 526 API, lifted to Lighthouse, lacks PACT Act support. A new PDF endpoint was created instead of updating the “containerized” EVSS API, as it’s being replaced soon.

- Was there a specific technical or business reason why the 526 PDF generation ended up in Lighthouse rather than vets-api?

> When a 526 claim is established in VBMS, the signed and date-stamped PDF must be sent to eFolder. Before Lighthouse had a 526 API, [VA.gov](http://va.gov/) used the EVSS API to ensure PDF delivery to eFolder. Prior to that, eBenefits/SEP users generated the PDF as part of the submission process. Therefore, when the EVSS API moved to Lighthouse, the 526 API remained responsible for PDFs.

Thanks so much for the quick response Michael!
Just to give you a bit more context, we're looking tweaking the overflow page of the PDF output to be more user-friendly for VSRs and Vets. Left = new version, right = current version.
...
If our goal here is to eventually update all VA Form PDFs, do you think there's an opportunity here to simplify and help create one PDF generator across all VA forms?

I think Lighthouse can accommodate the new overflow style. Please work with the Lighthouse PDF generator backend manager [robert.perea-martinez@adhocteam.us](mailto:robert.perea-martinez@adhocteam.us)
The 526 PDF generator has unique requirements that make it well suited to run on the system that generates claims and could complicate consolidation on vets-api.

- Stamp the top of each page with the claim ID
- Stamp the exact time the claim was submitted to VBMS
- Select the BDD claim type radio button and populate box 9 after confirming with Corp the user is eligible
- Parse service history to enter most recent dates
- Electronic POA signature
