### ISSUE TITLE
Investigate 10207 logic for VSI Flash

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3887]
## Issue Description
[Notes from 12/17/24 Sprint Planning]
- Follow-up research into applying VSI Flash #TODO Engineer
- Yang – yes it’s valuable. To confirm what the data sources is for VSI are what we actually want to use (might just be asking Alejandro). And based on knowing the data souce – how do we actually get access to that.

[Notes from 01/28/25 Sprint Planning]
- Yang - A little more research to do here, we can discuss in our next eng refinement.
- TLDR from meetings/research last week with Alejandro (see comments below): 
   - Leverage the 10207 since it’s a lower LOE than getting a new data source.
- What's left until we can begin engineering?

Background Info
- The VSI data is in DOD (not in VA land) and would be hard to get.
- There is a VA form (10207) for vets to self-attest to having "priority processing"
- Alejando let us know that we CAN rely on the 10207, for an MVP here to apply the VSI Flash.
- So...can we use the 10207? It doesn't have logic of it's own. It's part of the VFF teams team. They create all the forms that don't have special backend logic (a ton of others that should also be digitized, they have a way of easily converting these into a generic webform/backend)
- Is there a place on the backend, to insert our Flash setting logic?
- Note: in vets-api it's all done in the "simple forms API".
- If you file a 526, does it tell you in any way to file a 10207? Not sure. 
- Two ways forward:
   - Talk to the VFF team -- is there any precedent for what we're trying to do? Can they point us in the right direction?
   - POC this -- In case the VFF team gives us the go ahead, but doesn't give us pointers, we're still going to figure it out. Should this happen at the same time, or later?
- Another eng step -- figure out in our local VA env -- how to file an actual 10207 -- where does that data land, what does the payload look like? That will give us some good next steps for eng.

---
## Tasks
- [x] [...Refine more in our eng meeting -- week of 01/28/25, if needed]
- [x] Figure out what happens after we file a 10207 -- where does the data go, what does the payload look like? This should give us some good next steps toward a POC.
- [x] Mack to set up a meeting for VFF team next week.

## Acceptance Criteria
- [x] We know what data is created when you file a 10207.
- [x] We've met with the VFF team .
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`engineer`, `data science`, `design`, `research` , `product`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mackhowell-nava** [comment]
Original context here: https://github.com/department-of-veterans-affairs/abd-vro/issues/3708#issuecomment-2460480219

Open question from @nanotone for our next sync with Alejandro here:

To apply the VSI flash, are either of these options (more) correct and/or preferable?
- Fetching VSI status from DoD
- Watching for VSI to be claimed on a 20-10207 request for priority

**Comment by nanotone** [comment]
Some learnings from the 1/16 VBA sync:

- VBA has a "data matching" MOU with various agencies, including the DoD, which allows for data sync'ing (on the order of weekly, say) and VSI status would presumably be part of this data.
  - Alejandro has a point of contact who could provide more detail on how this is implemented.
- It should be possible to use the 20-10207 VSI checkbox as a proxy for applying VSI flash -- there are other situations where VBA relies on the Veteran's own layman attestation.
  - For a 10207 with VSI checked, a claims processor is supposed to evaluate the accompanying VSI evidence and can manually fix the flash if needed.
  - Veteran is supposed to submit the 526 and 10207 together, but on VA.gov the 10207 is a VFF and it's unclear how it would be part of the 526 flow. We should talk to the VFF team to learn more.
  - If we do use the 10207 and it is submitted after the 526, we should run it by Josh/NWQ to see if routing would be affected.

**Comment by mackhowell-nava** [comment]
Note from @nanotone  x Mack chat on 01/30/25:

- We're already going to chat with the VFF team(s) about the 4142 + combless form idea/work https://github.com/department-of-veterans-affairs/abd-vro/issues/3928
- We might need to talk to them about how we could hook into the 10207 logic to apply the VSI Flash -- since this is a VFF form as well

**Comment by mackhowell-nava** [comment]
Note from Alejandro from our EE/OBA sync on 02/06/25:

- Updates on how the VSI flash is determined/applied at the VA:
- Alejandro's been talking to a lot of people here, looking into it through his project directives...
- There is no external service to query DEERs or anything like that
- However, there is a third party program – IDES VTA, it’s either based on a verbal communication or email that triggers this work (so very manual)
- There are 3 forms:
   - 10-2743, 21-0773 (these are old, not sure if still used)
   - 10207 Request for Priority Processing -- requires Vets to self-attest. This would be the route to take...

**Comment by asiisii** [comment]
# 📝 Investigation: VA Form 20-10207 Submission Flow

## 1️⃣ Form API Requests
During testing in the **staging environment**, I identified three key API requests:

- **PUT Request** (Triggered on each form step update):  
  ``` /v0/in_progress_forms/20-10207 ```

- **Purpose**: Saves the current form state as the user progresses through different steps.
- **Triggered When**: The user updates any step of the form.
---
- **POST Request** (Supporting documents submission):  
```simple_forms_api/v1/simple_forms/submit_supporting_documents```

- **Purpose**: Uploads additional supporting documents (e.g., PDF evidence).
- **Triggered When**: The user uploads attachments before submitting.
---
- **POST Request** (Final form submission):  
  ``` /simple_forms_api/v1/simple_forms```

- **Purpose**: Submits the completed form for processing.
- **Triggered When**: The user clicks "Submit" at the end of the form.
---


---

## 2️⃣ Payload Sent on Final Submission

The following payload is sent when the form is submitted:
```
{
    "powConfinement2StartDate": "1979-02-01",
    "powConfinement2EndDate": "1980-02-01",
    "powConfinementStartDate": "1995-02-01",
    "powConfinementEndDate": "1996-02-01",
    "powMultipleConfinements": true,
    "otherReasons": {
        "FINANCIAL_HARDSHIP": true,
        "ALS": true,
        "TERMINAL_ILLNESS": true,
        "VSI_SI": true,
        "OVER_85": true,
        "FORMER_POW": true,
        "MEDAL_AWARD": true
    },
    "pointOfContactEmail": "vets.gov.user+12@gmail.com",
    "veteranPhone": "8008271000",
    "mailingAddressYesNo": false,
    "livingSituation": {
        "OVERNIGHT": true,
        "SHELTER": true,
        "FRIEND_OR_FAMILY": true,
        "LEAVING_SHELTER": true,
        "LOSING_HOME": true
    },
    "veteranId": {
        "ssn": "796186272"
    },
    "veteranFullName": {
        "first": "Jamie",
        "last": "Lee"
    },
    "veteranDateOfBirth": "1975-11-27",
    "preparerType": "veteran",
    "statementOfTruthSignature": "Jamie Lee",
    "statementOfTruthCertified": true,
    "formNumber": "20-10207"
}
```
