### ISSUE TITLE
VA Profile's Military Personnel Data documentation review, tech exploration definition, and access request tracking

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#78]
**Goal**: We'd like to understand what service history information is available in this API and how we might access it 

- [x] @amylai-nava - [Request access to VA Profile's Military Personnel Data](https://dsva.slack.com/archives/C01BVF2A3V0/p1655418391004909) - form submitted 6/20
- [x] @allthesignals & @amylai-nava - review information about Military Personnel Data [here](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/Military-Personnel-Data.aspx) and [here](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/VA-Profile-SwaggerUI-Links.aspx?csf=1&web=1&e=lBdP8h). Document notes & open questions in this ticket.
- [ ] @allthesignals & @amylai-nava - discuss/define tech exploration after documentation review^ 
- [ ] @amylai-nava - monitor access request

Later, pending VA Profile access: pull service history for the new claims we identified
 
**Context**:
* VA Profile's API will be replacing the VADIR eligibility API, which is being deprecated
* [Slack thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1654615273380869?thread_ts=1654613058.484109&cid=C01BVF2A3V0)
* Note: if accessing the Sharepoint sites from GFE just use Edge, do not try to sign-in through Chrome
